// ---------------------------------------------------------------------------
// All editable site copy lives here, in English and Chinese.
// This file is regenerated by editor.html — hand-written comments here will
// be lost on save, but the data structure and all page scripts are unaffected.
// ---------------------------------------------------------------------------

const SITE_CONTENT = {
  "en": {
    "nav": {
      "home": "HOME",
      "about": "ABOUT",
      "projects": "PROJECTS",
      "experience": "EXPERIENCE",
      "education": "EDUCATION",
      "writing": "BLOG",
      "beyondWork": "BEYOND GAME",
      "aiTool": "AI RELATED",
      "contact": "CONTACT",
      "aboutFull": "ABOUT ME",
      "resume": "RESUME"
    },
    "site": {
      "name": "YOUNG GOU"
    },
    "hero": {
      "eyebrow": "",
      "name": "YOUNG GOU",
      "nameLines": [
        "YOUNG GOU"
      ],
      "portrait": "images/presentation.jpg",
      "navPhoto": "images/portrait.jpg",
      "workPhotos": [
        "images/work/work-1.jpg",
        "images/work/work-2.jpg",
        "images/work/work-3.jpg"
      ],
      "role": "Producer/Project manager",
      "intro": "Passion-Driven; ACG Enthusiast; Servant Leadership",
      "scroll": "SCROLL"
    },
    "home": {
      "teamProjectsHeading": "Team Projects",
      "resumeCard": {
        "title": "Resume",
        "body": "Full work history, skills, and education.",
        "cta": "View resume"
      },
      "aboutCard": {
        "title": "About Me",
        "body": "Who I am, how I got here, and what's next.",
        "cta": "Read more"
      },
      "contactHeading": "Contact"
    },
    "about": {
      "heading": "About",
      "lead": "My passion lies in game production, leading diverse cross-disciplinary teams to create fantastic games.",
      "body": "Producer with experience of managing multidisciplinary teams and optimization pipelines. I fuse a background in architecture with expertise in game systems design to bring a structural approach to project logistics, scope management, and cross-departmental communication.",
      "readMore": "Read the full story",
      "readMoreHref": "about.html",
      "skills": [
        "Project Management",
        "Jira",
        "Agile",
        "Lark",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity"
      ]
    },
    "projects": {
      "heading": "Projects",
      "relatedHeading": "Related Projects",
      "items": [
        {
          "title": "Box Shot",
          "tag": "GAME PROJECT",
          "role": "Producer",
          "summary": "Placeholder — one or two sentences on what the game is and what you contributed.",
          "href": "team-projects/capstone.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "title": "Hamsterballin'",
          "tag": "GAME PROJECT",
          "role": "Producer",
          "summary": "A Mario Kart-style racing game built in Unreal Engine 5, on Steam.",
          "href": "team-projects/tgp2.html",
          "image": "images/hamsterballin-card.jpg",
          "placeholder": false
        },
        {
          "title": "Detective Folder",
          "tag": "GAME PROJECT",
          "role": "Level Designer",
          "summary": "A 2D puzzle-platformer where a detective folds a living comic-book world to gather clues and catch the \"Baahd Guys.\"",
          "href": "team-projects/tgp1.html",
          "image": "images/detective-folder-card.jpg",
          "placeholder": false
        },
        {
          "title": "Heart Arsonist",
          "tag": "GAME PROJECT",
          "role": "Producer / Level Designer",
          "summary": "A 2.5D game demo built with the Tuanjie Engine — a Unity Game Jam entry that took bronze.",
          "href": "individual-projects/fire.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "teamProjects": {
      "heading": "Team Projects",
      "intro": "Game projects built with cross-functional student and studio teams.",
      "list": [
        {
          "id": "capstone",
          "tag": "CAPSTONE GAME PROJECT",
          "name": "Box Shot",
          "role": "Producer",
          "teamSize": "Placeholder",
          "length": "Placeholder",
          "blurb": "Placeholder — one-line description of the game.",
          "href": "team-projects/capstone.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "tgp2",
          "tag": "GAME PROJECT",
          "name": "Hamsterballin'",
          "role": "Producer",
          "teamSize": "43",
          "length": "1 semester",
          "blurb": "A Mario Kart-style racing game built in Unreal Engine 5, on Steam.",
          "href": "team-projects/tgp2.html",
          "image": "images/hamsterballin-card.jpg",
          "placeholder": false
        },
        {
          "id": "tgp1",
          "tag": "GAME PROJECT",
          "name": "Detective Folder",
          "role": "Level Designer",
          "teamSize": "5",
          "length": "1 semester",
          "blurb": "A 2D puzzle-platformer built in Unity where a detective folds a living comic-book world to catch the \"Baahd Guys.\"",
          "href": "team-projects/tgp1.html",
          "image": "images/detective-folder-card.jpg",
          "placeholder": false
        }
      ]
    },
    "tgp2": {
      "backLink": "← Back to Projects",
      "tagLabel": "GAME PROJECT",
      "gameName": "Hamsterballin'",
      "image": "../images/hamsterballin-hero.jpg",
      "roleLabel": "Role",
      "role": "Producer",
      "teamSizeLabel": "Team Size",
      "teamSize": "43",
      "lengthLabel": "Length",
      "length": "1 semester",
      "platformLabel": "Platform",
      "platform": "PC (Steam) — Unreal Engine 5",
      "synopsisHeading": "Synopsis",
      "synopsis": "Hamsterballin' is a fast-paced racing game built in Unreal Engine 5 by a 43-person cross-functional student team of designers, artists, and programmers, released on Steam.",
      "trailerHeading": "Trailer",
      "trailerNote": "Gameplay trailer.",
      "trailerVideoId": "SGqrpin8Yuk",
      "responsibilitiesHeading": "Responsibilities",
      "responsibilities": [
        "Led a 43-person cross-functional team of designers, artists, and programmers through the full development cycle.",
        "Facilitated Agile/Scrum methodologies for a large-scale student team — sprint planning, daily stand-ups, and retrospectives — to ensure timely milestone deliveries.",
        "Managed project schedules and task tracking to mitigate scope creep and resolve development bottlenecks across multiple disciplines.",
        "Coordinated regular playtesting sessions, synthesizing player feedback to guide iterative design improvements and performance optimizations."
      ],
      "screenshotsHeading": "Screenshots",
      "screenshotsNote": "Placeholder — add gameplay screenshots.",
      "postmortemHeading": "Postmortem",
      "postmortem": "Placeholder — reflect on what went well, what you'd do differently, and what you learned."
    },
    "tgp1": {
      "backLink": "← Back to Projects",
      "tagLabel": "GAME PROJECT",
      "gameName": "Detective Folder",
      "image": "../images/detective-folder-hero.jpg",
      "roleLabel": "Role",
      "role": "Level Designer",
      "teamSizeLabel": "Team Size",
      "teamSize": "5",
      "lengthLabel": "Length",
      "length": "1 semester",
      "platformLabel": "Platform",
      "platform": "PC — Unity (SMU Guildhall)",
      "synopsisHeading": "Synopsis",
      "synopsis": "Detective Folder is a 2D puzzle-platformer built in Unity by a 5-person student team, in which you play a detective for the clandestine Anomalous Crimes Unit — folding a living comic-book world to reshape platforms, uncover clues, and track down the \"Baahd Guys.\"",
      "trailerHeading": "Trailer",
      "trailerNote": "Gameplay trailer.",
      "trailerVideoId": "caEVKftmSHA",
      "responsibilitiesHeading": "Responsibilities",
      "responsibilities": [
        "Designed the Tutorial level, the second half of Level 1, and all of Level 3 and Level 4, systematically introducing and reinforcing the game's core folding mechanic.",
        "Proposed and took ownership of the \"folding\" mechanic during initial brainstorming, exploring its use for both spatial navigation and puzzle depth across the game.",
        "Worked directly with the team's programmer to establish technical constraints before committing to level layouts, and helped troubleshoot implementation issues.",
        "Facilitated open, honest communication within the team to resolve early interpersonal friction, adapting my approach to each teammate's working style.",
        "Contributed to the GDD/LDD documentation and helped the art team align on visual direction."
      ],
      "screenshotsHeading": "Screenshots",
      "screenshotsNote": "Tutorial, Level 3's diagonal-folding maze, and Level 4's dinosaur encounters.",
      "screenshots": [
        "../images/detective-folder/shot-2.jpg",
        "../images/detective-folder/shot-3.jpg",
        "../images/detective-folder/shot-4.jpg",
        "../images/detective-folder/shot-1.jpg"
      ],
      "postmortemHeading": "Postmortem",
      "postmortem": "Owning the folding mechanic from initial concept through four levels taught me to treat failure as data — with no existing reference for this kind of mechanic, I leaned on a \"fail fast\" approach to keep iterating at speed. The biggest lesson was around scope: features like Level 4's dinosaurs were fun but expensive, and without rigorous asset-lock discipline we spent time on spectacle instead of polish. I also learned to bring in playtesters earlier — by the time we saw players struggle with onboarding, it was late enough that we had to scramble to rebuild the tutorial. Above all, this project taught me the value of pre-production technical validation and clear documentation as a single source of truth for a team working through a genuinely novel mechanic."
    },
    "capstone": {
      "backLink": "← Back to Projects",
      "tagLabel": "CAPSTONE PROJECT (PLACEHOLDER)",
      "gameName": "Box Shot",
      "image": "../images/project-placeholder.svg",
      "roleLabel": "Role",
      "role": "Producer",
      "teamSizeLabel": "Team Size",
      "teamSize": "Placeholder",
      "lengthLabel": "Length",
      "length": "Placeholder",
      "platformLabel": "Platform",
      "platform": "Placeholder",
      "synopsisHeading": "Synopsis",
      "synopsis": "Placeholder — this project's details are pending. Replace with a real synopsis when ready.",
      "trailerHeading": "Trailer",
      "trailerNote": "Placeholder — embed the game trailer here.",
      "responsibilitiesHeading": "Responsibilities",
      "responsibilities": [
        "Placeholder — list your specific responsibilities and contributions."
      ],
      "screenshotsHeading": "Screenshots",
      "screenshotsNote": "Placeholder — add gameplay screenshots.",
      "postmortemHeading": "Postmortem",
      "postmortem": "Placeholder — reflect on what went well, what you'd do differently, and what you learned."
    },
    "individualProjects": {
      "heading": "Individual Projects & Certifications",
      "intro": "Independent work, including your Directed Focus Study (DFS) or thesis project.",
      "list": [
        {
          "id": "fire",
          "tag": "INDIVIDUAL PROJECT",
          "name": "Heart Arsonist",
          "blurb": "A 2.5D game demo built with the Tuanjie Engine — a Unity Game Jam entry that took bronze.",
          "href": "individual-projects/fire.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "fire": {
      "backLink": "← Back to Projects",
      "tagLabel": "INDIVIDUAL PROJECT (PLACEHOLDER)",
      "projectName": "Heart Arsonist",
      "image": "../images/project-placeholder.svg",
      "roleLabel": "Role",
      "role": "Producer / Level Designer",
      "teamSizeLabel": "Team Size",
      "teamSize": "Placeholder (e.g. Solo)",
      "lengthLabel": "Length",
      "length": "Placeholder",
      "synopsisHeading": "Synopsis",
      "synopsis": "Placeholder — describe the project, even if it's a work in progress.",
      "trailerHeading": "Trailer",
      "trailerNote": "Gameplay trailer.",
      "trailerVideoId": "713lnqBMnyk",
      "responsibilitiesHeading": "Responsibilities",
      "responsibilities": [
        "Placeholder — list your specific responsibilities and contributions."
      ],
      "screenshotsHeading": "Screenshots",
      "screenshotsNote": "Placeholder — add project screenshots.",
      "postmortemHeading": "Postmortem",
      "postmortem": "Placeholder — reflect on what went well, what you'd do differently, and what you learned."
    },
    "aboutPage": {
      "pageTitle": "Young Gou — About Me",
      "heading": "About Me",
      "photoAlt": "Professional portrait placeholder",
      "whoHeading": "Who I am & what I'm doing",
      "who": "Producer with experience of managing multidisciplinary teams and optimization pipelines. I fuse a background in architecture with expertise in game systems design to bring a unique, structural approach to project logistics, scope management, and cross-departmental communication. Highly skilled at facilitating alignment between creative and design disciplines to deliver polished, mechanically sound projects.",
      "howHeading": "How I got here",
      "how": "Placeholder — a short narrative connecting your architecture background to your move into game production (e.g. what drew you from buildings to games).",
      "nextHeading": "Where I'm looking to go next",
      "next": "Placeholder — describe the kind of role, studio, or team you're hoping to join next.",
      "funHeading": "A few fun facts",
      "fun": "Placeholder — a couple of light, personal details (hobbies, favorite games, etc.) that show your voice."
    },
    "beyondWorkPage": {
      "pageTitle": "Young Gou — Beyond Game",
      "heading": "Beyond Game",
      "lead": "Placeholder — a short introduction to who you are outside of games and work.",
      "galleryHeading": "Photo Wall",
      "galleryNote": "Placeholder — swap these for real photos any time.",
      "photos": [
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" },
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" },
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" },
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" },
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" },
        { "src": "images/project-placeholder.svg", "caption": "Placeholder caption" }
      ],
      "sectionsHeading": "Sections",
      "sectionsIntro": "Four things I spend my time on when I'm not producing games.",
      "sections": [
        {
          "id": "photography",
          "tag": "PHOTOGRAPHY",
          "name": "Photography",
          "blurb": "Placeholder — what you shoot and why you keep doing it.",
          "href": "beyond-work/photography.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "architecture",
          "tag": "ARCHITECTURE",
          "name": "Architecture",
          "blurb": "Placeholder — the background that still shapes how you look at space.",
          "href": "beyond-work/architecture.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "travel",
          "tag": "TRAVEL",
          "name": "Travel",
          "blurb": "Placeholder — where you've been and what you brought back.",
          "href": "beyond-work/travel.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "cooking",
          "tag": "COOKING",
          "name": "Cooking",
          "blurb": "Placeholder — what you cook and who you cook it for.",
          "href": "beyond-work/cooking.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "aiToolPage": {
      "pageTitle": "Young Gou — AI Playtest Feedback Tool",
      "tagLabel": "AI DEMO",
      "heading": "AI Playtest Feedback Triage",
      "lead": "A small tool I built to show hands-on experience applying AI to a real production workflow: paste raw playtest feedback and it comes back triaged the way a producer would triage it by hand after a session — split into individual findings, each tagged with what kind of work it is and how badly it hurts.",
      "disclaimer": "This calls a small serverless function backed by a language model. Nothing you paste here is stored — it's only used to generate the categorized summary below.",
      "inputLabel": "Paste playtest feedback",
      "inputPlaceholder": "Paste one or more playtesters' written feedback here…",
      "sampleButton": "Load sample feedback",
      "sampleText": "Playtest session notes — build 0.4.2, 6 testers, 45 min each.\n\nTwo testers hit a hard crash when they opened the map during the boss fight. One of them lost about 40 minutes of progress because the last checkpoint was before the arena.\nThree people had no idea the dash existed until the second area. Two of them said there should be a prompt at the first gap you can't clear with a normal jump.\nBoss two is a wall — four testers died more than five times on it. One said outright \"boss three felt easier than boss two\".\nThe market scene dropped to slideshow framerate on both laptops, fine on the desktop.\nOne tester read the save icon as a delete button and avoided it for the whole session.\nEveryone liked the art. Three brought up the level 2 music without being asked.\nTwo asked for remappable controls — one said jump on B hurts their hand after 20 minutes; they suggested a key-binding screen in the options menu.\nSubtitle text overlaps the portrait at 1080p, but nobody seemed bothered by it.",
      "submitButton": "Analyze feedback",
      "loadingLabel": "Analyzing…",
      "summaryHeading": "Summary",
      "emptyCategoryNote": "No categories were flagged in this feedback.",
      "errorEmpty": "Paste some feedback first.",
      "errorTooLong": "That's a lot of text — please keep it under 4000 characters.",
      "errorNotConfigured": "This demo's backend hasn't been deployed yet — check back soon.",
      "errorRequestFailed": "Something went wrong reaching the AI service. Please try again in a moment.",
      "rateLimitNote": "Limited to {limit} analyses per day on this demo to keep hosting costs in check. {remaining} left today.",
      "rateLimitReached": "You've used all {limit} analyses available today on this demo — please come back tomorrow.",
      "taxonomyNote": "Every point is classified on two axes: what kind of work it is (type), and how much it hurts (severity). Type routes the work; severity and how often players raised it decide what gets done first.",
      "priorityHeading": "Fix first",
      "mentionsLabel": "raised {n}x",
      "playerFixLabel": "Player's suggested fix",
      "typeLabels": {
        "bug": "Bugs",
        "performance": "Performance",
        "usability": "Usability",
        "balance": "Balance",
        "content": "Content",
        "request": "Feature requests",
        "other": "Other",
        "positive": "What worked"
      },
      "severityLabels": {
        "critical": "Critical",
        "major": "Major",
        "minor": "Minor",
        "unrated": "Unrated"
      }
    },
    "skills": {
      "heading": "Skills",
      "items": [
        "Project Management",
        "Jira",
        "Agile",
        "Lark",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity"
      ],
      "languagesLabel": "Languages",
      "languages": [
        "English",
        "Chinese (Mandarin)"
      ]
    },
    "experience": {
      "heading": "Experience",
      "items": [
        {
          "title": "Systems Designer Intern",
          "org": "Lilith Games",
          "location": "Shanghai, China",
          "dates": "04/2025 — 08/2025",
          "bullets": [
            "Designed systems for the AFK Arena project, working with multidiscipline teams, enhancing large-scale, in-game SLG mechanics for improved player engagement.",
            "Developed and balanced a new PvP ranking system by communicating with leads and others to meet their goals, aiming to elevate the competitive gameplay experience."
          ]
        },
        {
          "title": "Architectural Intern",
          "org": "China Southwest Architectural Design and Research Institute (CSWADI)",
          "location": "Chengdu, China",
          "dates": "08/2022 — 11/2022",
          "bullets": [
            "Developed three preliminary design proposals, presented pitches to stakeholders, refined architectural details, and finalized the facade design for the Second University Hospital of West China, improving project alignment with client vision."
          ]
        }
      ]
    },
    "education": {
      "heading": "Education",
      "items": [
        {
          "degree": "Master's: Interactive Technology, Digital Game Development — Production Track",
          "school": "Southern Methodist University (SMU) Guildhall",
          "location": "Dallas, TX, USA",
          "dates": "Expected 06/2027"
        },
        {
          "degree": "Bachelor of Architecture",
          "school": "Tianjin University",
          "location": "Tianjin, China",
          "dates": "06/2023"
        }
      ]
    },
    "blog": {
      "heading": "Writing",
      "viewAll": "View all writing",
      "recentLabel": "Recent Posts",
      "viewAllPosts": "View all posts",
      "items": [
        {
          "slug": "lessons-from-gearbox",
          "title": "Lessons from Gearbox",
          "date": "Date TBD",
          "category": "Career",
          "excerpt": "Notes from a studio visit with Gearbox's EP and assistant director of production — on feedback, communication, and what a producer's job really is.",
          "pullQuote": "Friendship leads to ship — but it doesn't mean we have to do everything for them.",
          "body": [
            "Last week we met with J. Low, the executive producer, and Lou, the assistant director of production.",
            "Both of them hold “high-level” positions, and the first impression was how different their communication style is from producers I've met before — very straightforward, with almost no wasted words. It made me think about whether I sometimes communicate just for the sake of communicating; speaking more doesn't necessarily make me a better communicator. Beyond talking, they both used hand-drawing to make their points clearer, which reminded me of my time as an architect, when we used hand-drawing to communicate with clients. It's been a long time since I stopped — I don't even remember why — but I think it's worth picking back up as a “weapon” for communication.",
            "We talked a lot about career development.",
            "How to take feedback? J. Low said everyone has blind spots — think about “what am I not seeing,” and stay open to feedback, especially from people you don't naturally get along with. Once you get feedback, think about the reason behind it: if it's negative, why? Is it constructive? How can I change? If I still don't understand, go talk to that person directly.",
            "How to give feedback? Be direct and constructive. Lou said there's no need for the “compliment sandwich,” which I found genuinely useful. But being direct doesn't mean being harsh — I still try to give feedback with appreciation for the other person's contribution.",
            "Lou also mentioned the four stages of competence: unconscious incompetence, conscious incompetence, conscious competence, and unconscious competence. We're always somewhere on that loop.",
            "Lou also talked about the “empathy shift” over the course of a career. Honestly, I'm not sure yet what to do with that, but I assume it'll matter more once I'm actually in the industry.",
            "What is a producer's job, really? That was the other big question we discussed. TL;DR: “maintain the momentum.” One of the biggest traps junior producers fall into is over-investing emotionally in their team or leads. “Friendship leads to ship” — but that doesn't mean doing everything for them. Learning to scale your work is essential, because the job itself changes with every promotion.",
            "Last but not least — resume tips: no photo, no AI-written cover letters, and use strong, active language (“I drove...”) instead of passive phrasing (“I was participating in...”). That one really landed for me."
          ]
        },
        {
          "title": "Placeholder article title",
          "date": "Date",
          "category": "Design"
        },
        {
          "title": "Placeholder article title",
          "date": "Date",
          "category": "Postmortem"
        }
      ]
    },
    "personalProjects": {
      "heading": "Personal Projects",
      "intro": "Placeholder — side projects, game jams, or explorations outside of school/work.",
      "items": [
        {
          "title": "Placeholder project",
          "blurb": "Placeholder — short description.",
          "href": "#"
        }
      ]
    },
    "contact": {
      "heading": "Contact",
      "lead": "Let's talk about games, teams, or opportunities.",
      "locationLabel": "Location",
      "location": "Dallas, TX 75206",
      "emailLabel": "Email",
      "email": "ygou920@gmail.com",
      "websiteLabel": "LinkedIn",
      "website": "https://www.linkedin.com/in/young-gou-97b184381/"
    },
    "footer": {
      "note": "Built with care. All rights reserved."
    },
    "resumePage": {
      "pageTitle": "Young Gou — Resume",
      "title": "Resume",
      "roleTag": "Game Producer",
      "downloadPdf": "Download PDF",
      "backHome": "← Back to site",
      "embedHeading": "Embedded Resume (PDF)",
      "embedNote": "Generated from your resume draft. Replace ZhongyinGou_resume.pdf with a newer export any time and this preview updates automatically.",
      "summaryHeading": "Summary",
      "summary": "Producer with several years of experience managing multidisciplinary teams and optimization pipelines. Fuses a background in architecture with expertise in game systems design to bring a unique, structural approach to project logistics, scope management, and cross-departmental communication.",
      "contactHeading": "Contact",
      "experienceHeading": "Experience",
      "educationHeading": "Education",
      "skillsHeading": "Skills",
      "projectsHeading": "Selected Projects"
    },
    "gameAnalysis": {
      "heading": "Game Analysis",
      "intro": "Teardowns of the systems, economies and level flow behind games I keep coming back to.",
      "list": [
        {
          "id": "analysis-1",
          "tag": "ANALYSIS · TBD",
          "name": "Analysis one — title TBD",
          "blurb": "Placeholder — one line on which game you pulled apart and what the takeaway was.",
          "href": "game-analysis/analysis-1.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "analysis-2",
          "tag": "ANALYSIS · TBD",
          "name": "Analysis two — title TBD",
          "blurb": "Placeholder — one line on which game you pulled apart and what the takeaway was.",
          "href": "game-analysis/analysis-2.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "analysis-3",
          "tag": "ANALYSIS · TBD",
          "name": "Analysis three — title TBD",
          "blurb": "Placeholder — one line on which game you pulled apart and what the takeaway was.",
          "href": "game-analysis/analysis-3.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "aiHubPage": {
      "pageTitle": "Young Gou — AI",
      "tagLabel": "AI",
      "heading": "AI Work",
      "lead": "Small experiments and working tools built with AI — pick one to open it.",
      "projectsHeading": "AI Side Projects",
      "projectsIntro": "Prototypes and experiments, mostly built to answer a question.",
      "projects": [
        {
          "id": "ai-project-1",
          "tag": "SIDE PROJECT · TBD",
          "name": "AI project one — title TBD",
          "blurb": "Placeholder — one line on what it does and what you learned.",
          "href": "ai-projects/project-1.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "ai-project-2",
          "tag": "SIDE PROJECT · TBD",
          "name": "AI project two — title TBD",
          "blurb": "Placeholder — one line on what it does and what you learned.",
          "href": "ai-projects/project-2.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ],
      "toolsHeading": "AI Tools",
      "toolsIntro": "Tools you can actually run right here in the browser.",
      "tools": [
        {
          "id": "playtest",
          "tag": "LIVE TOOL",
          "name": "Playtest Feedback Sorter",
          "blurb": "Paste raw playtest feedback and get it grouped into themes by an AI model.",
          "href": "ai-tools/playtest-feedback.html",
          "image": "images/project-placeholder.svg",
          "placeholder": false
        },
        {
          "id": "reffix",
          "tag": "LIVE TOOL",
          "name": "RefFix — Reference Formatter",
          "blurb": "Reformats a reference list into IEEE, APA 7 or MLA 9 — rule set first, AI only where the rules run out. Runs entirely in your browser.",
          "href": "ai-tools/reffix.html",
          "image": "images/reffix-cover.svg",
          "placeholder": false
        }
      ]
    },
    "stories": {
      "photography": {
        "pageTitle": "Young Gou — Photography",
        "tagLabel": "PHOTOGRAPHY",
        "heading": "Photography",
        "lead": "Placeholder — a line or two about how you got into shooting and what you look for.",
        "backLink": "← Back to Beyond Game",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "architecture": {
        "pageTitle": "Young Gou — Architecture",
        "tagLabel": "ARCHITECTURE",
        "heading": "Architecture",
        "lead": "Placeholder — how an architecture background still shapes the way you read space.",
        "backLink": "← Back to Beyond Game",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "travel": {
        "pageTitle": "Young Gou — Travel",
        "tagLabel": "TRAVEL",
        "heading": "Travel",
        "lead": "Placeholder — where you've been and what stuck with you.",
        "backLink": "← Back to Beyond Game",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "cooking": {
        "pageTitle": "Young Gou — Cooking",
        "tagLabel": "COOKING",
        "heading": "Cooking",
        "lead": "Placeholder — what you cook, and what cooking has in common with production.",
        "backLink": "← Back to Beyond Game",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "analysis-1": {
        "pageTitle": "Young Gou — Game Analysis",
        "tagLabel": "ANALYSIS · TBD",
        "heading": "Analysis one — title TBD",
        "lead": "Placeholder — which game, and the question you were trying to answer.",
        "backLink": "← Back to Projects",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "analysis-2": {
        "pageTitle": "Young Gou — Game Analysis",
        "tagLabel": "ANALYSIS · TBD",
        "heading": "Analysis two — title TBD",
        "lead": "Placeholder — which game, and the question you were trying to answer.",
        "backLink": "← Back to Projects",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "analysis-3": {
        "pageTitle": "Young Gou — Game Analysis",
        "tagLabel": "ANALYSIS · TBD",
        "heading": "Analysis three — title TBD",
        "lead": "Placeholder — which game, and the question you were trying to answer.",
        "backLink": "← Back to Projects",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "ai-project-1": {
        "pageTitle": "Young Gou — AI Project",
        "tagLabel": "SIDE PROJECT · TBD",
        "heading": "AI project one — title TBD",
        "lead": "Placeholder — what you built and why.",
        "backLink": "← Back to AI",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "ai-project-2": {
        "pageTitle": "Young Gou — AI Project",
        "tagLabel": "SIDE PROJECT · TBD",
        "heading": "AI project two — title TBD",
        "lead": "Placeholder — what you built and why.",
        "backLink": "← Back to AI",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      },
      "tool-2": {
        "pageTitle": "Young Gou — AI Tool",
        "tagLabel": "TOOL · TBD",
        "heading": "Tool two — title TBD",
        "lead": "Placeholder — what this tool will do once it's built.",
        "backLink": "← Back to AI",
        "blocks": [
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          },
          {
            "heading": "Placeholder heading",
            "text": "Placeholder — swap this paragraph for the real story. Two or three sentences works best next to an image.",
            "image": "images/project-placeholder.svg",
            "caption": "Placeholder caption"
          }
        ]
      }
    },
    "reffixPage": {
      "pageTitle": "Young Gou — RefFix",
      "tagLabel": "LIVE TOOL · OPEN SOURCE",
      "heading": "RefFix",
      "lead": "A tool I built to reformat academic reference lists into IEEE, APA 7 or MLA 9 — and to be honest about what it cannot fix.",
      "backLink": "← Back to AI",
      "whyHeading": "Why",
      "why": "Reference formatting is mechanical work that still eats an evening before every submission, and the errors are the kind a human reader catches instantly but a writer stops seeing after the fourth pass. It is exactly the sort of task worth automating: high volume, low judgement, clearly specified by a published style guide.",
      "howHeading": "How it works",
      "how": "A deterministic rule set does the bulk of the job — parsing each entry into fields, then re-rendering them in the target style. AI is used only where the rules genuinely run out: entries that are malformed, ambiguous, or written in a style the parser doesn't recognise. Rules first, model second, because a rule that is wrong is a bug you can fix once, while a model that is wrong is a surprise every time.",
      "principleHeading": "The one rule it never breaks",
      "principle": "It never invents facts about a source. If a DOI, page range or publisher is missing, the tool flags the entry instead of filling the gap with something plausible — a fabricated citation is worse than an unformatted one.",
      "privacyHeading": "Where it runs",
      "privacy": "The entire Python pipeline runs inside the browser through Pyodide. There is no backend: the document you drop in never leaves your device, which also means the tool costs nothing to host and keeps working if I stop maintaining the server side.",
      "openLabel": "Open the full tool",
      "repoLabel": "Source on GitHub",
      "embedNote": "The live tool is embedded below. It also runs standalone — use the button above if you'd rather have the full window.",
      "embedUrl": "https://younago.github.io/IEEE-Format-Correct/",
      "repoUrl": "https://github.com/Younago/IEEE-Format-Correct"
    }
  },
  "zh": {
    "nav": {
      "home": "首页",
      "about": "关于我",
      "projects": "项目作品",
      "experience": "工作经历",
      "education": "教育背景",
      "writing": "博客",
      "beyondWork": "游戏之外",
      "aiTool": "AI 相关",
      "contact": "联系方式",
      "aboutFull": "关于我（详情）",
      "resume": "简历"
    },
    "site": {
      "name": "苟阳"
    },
    "hero": {
      "eyebrow": "",
      "name": "苟阳",
      "nameLines": [
        "YOUNG GOU"
      ],
      "portrait": "images/presentation.jpg",
      "navPhoto": "images/portrait.jpg",
      "workPhotos": [
        "images/work/work-1.jpg",
        "images/work/work-2.jpg",
        "images/work/work-3.jpg"
      ],
      "role": "Producer/Project manager",
      "intro": "Passion-Driven; ACG Enthusiast; Servant Leadership",
      "scroll": "Scroll"
    },
    "home": {
      "teamProjectsHeading": "团队项目",
      "resumeCard": {
        "title": "简历",
        "body": "完整的工作经历、技能与教育背景。",
        "cta": "查看简历"
      },
      "aboutCard": {
        "title": "关于我",
        "body": "我是谁、我如何走到这里，以及接下来的方向。",
        "cta": "了解更多"
      },
      "contactHeading": "联系方式"
    },
    "about": {
      "heading": "关于我",
      "lead": "我的热情在于游戏制作，带领多元的跨领域团队打造出色的游戏。",
      "body": "我是一名拥有多年跨领域团队管理和流程优化经验的制作人。我将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种结构化的方法。",
      "readMore": "查看完整介绍",
      "readMoreHref": "about.html",
      "skills": [
        "项目管理",
        "Jira",
        "敏捷开发",
        "Lark 飞书",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity"
      ]
    },
    "projects": {
      "heading": "项目",
      "relatedHeading": "相关项目",
      "items": [
        {
          "title": "Box Shot",
          "tag": "游戏项目",
          "role": "制作人",
          "summary": "占位文字 — 一两句话介绍这款游戏和你的具体贡献。",
          "href": "team-projects/capstone.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "title": "Hamsterballin'",
          "tag": "游戏项目",
          "role": "制作人",
          "summary": "一款用 Unreal Engine 5 制作的类马里奥赛车竞速游戏，已上线 Steam。",
          "href": "team-projects/tgp2.html",
          "image": "images/hamsterballin-card.jpg",
          "placeholder": false
        },
        {
          "title": "Detective Folder",
          "tag": "游戏项目",
          "role": "关卡策划",
          "summary": "一款 2D 解谜平台游戏，玩家扮演侦探折叠一个活生生的漫画世界，收集线索并抓捕「坏蛋」。",
          "href": "team-projects/tgp1.html",
          "image": "images/detective-folder-card.jpg",
          "placeholder": false
        },
        {
          "title": "芳心纵火犯",
          "tag": "游戏项目",
          "role": "制作人/关卡策划",
          "summary": "一款用团结引擎制作的 2.5D 游戏 demo，参加 Unity Game Jam 并获铜奖。",
          "href": "individual-projects/fire.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "teamProjects": {
      "heading": "团队项目",
      "intro": "与跨职能的学生团队及工作室团队共同完成的游戏项目。",
      "list": [
        {
          "id": "capstone",
          "tag": "CAPSTONE GAME PROJECT",
          "name": "Box Shot",
          "role": "制作人",
          "teamSize": "占位",
          "length": "占位",
          "blurb": "占位文字 — 一句话介绍这款游戏。",
          "href": "team-projects/capstone.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "tgp2",
          "tag": "游戏项目",
          "name": "Hamsterballin'",
          "role": "制作人",
          "teamSize": "43",
          "length": "1 学期",
          "blurb": "一款用 Unreal Engine 5 制作的类马里奥赛车竞速游戏，已上线 Steam。",
          "href": "team-projects/tgp2.html",
          "image": "images/hamsterballin-card.jpg",
          "placeholder": false
        },
        {
          "id": "tgp1",
          "tag": "游戏项目",
          "name": "Detective Folder",
          "role": "关卡策划",
          "teamSize": "5",
          "length": "1 学期",
          "blurb": "一款用 Unity 制作的 2D 解谜平台游戏，玩家折叠漫画世界来抓捕「Baahd Guys」。",
          "href": "team-projects/tgp1.html",
          "image": "images/detective-folder-card.jpg",
          "placeholder": false
        }
      ]
    },
    "tgp2": {
      "backLink": "← 返回项目",
      "tagLabel": "游戏项目",
      "gameName": "Hamsterballin'",
      "image": "../images/hamsterballin-hero.jpg",
      "roleLabel": "角色",
      "role": "制作人",
      "teamSizeLabel": "团队规模",
      "teamSize": "43 人",
      "lengthLabel": "项目周期",
      "length": "1 学期",
      "platformLabel": "平台",
      "platform": "PC（Steam）— Unreal Engine 5",
      "synopsisHeading": "游戏简介",
      "synopsis": "Hamsterballin' 是一款用 Unreal Engine 5 制作的快节奏竞速游戏，由一支 43 人的跨职能学生团队（设计、美术、程序）共同完成，已上线 Steam。",
      "trailerHeading": "预告片",
      "trailerNote": "游戏预告片。",
      "trailerVideoId": "SGqrpin8Yuk",
      "responsibilitiesHeading": "主要职责",
      "responsibilities": [
        "带领一支由设计师、美术和程序员组成的 43 人跨职能团队，完成了完整的开发周期。",
        "为大规模学生团队推行 Agile/Scrum 方法论——冲刺规划、每日站会与复盘——确保各里程碑按时交付。",
        "管理项目进度与任务追踪，控制范围蔓延，解决跨多个专业方向的开发瓶颈。",
        "统筹定期的玩家测试环节，综合玩家反馈以指导迭代设计改进与性能优化。"
      ],
      "screenshotsHeading": "游戏截图",
      "screenshotsNote": "占位 — 添加游戏截图。",
      "postmortemHeading": "项目复盘",
      "postmortem": "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。"
    },
    "tgp1": {
      "backLink": "← 返回项目",
      "tagLabel": "游戏项目",
      "gameName": "Detective Folder",
      "image": "../images/detective-folder-hero.jpg",
      "roleLabel": "角色",
      "role": "关卡策划",
      "teamSizeLabel": "团队规模",
      "teamSize": "5 人",
      "lengthLabel": "项目周期",
      "length": "1 学期",
      "platformLabel": "平台",
      "platform": "PC — Unity（SMU Guildhall）",
      "synopsisHeading": "游戏简介",
      "synopsis": "Detective Folder 是一款由 5 人学生团队用 Unity 制作的 2D 解谜平台游戏。玩家扮演神秘「异常犯罪调查组」的侦探，通过折叠这个如漫画书般鲜活的世界来改变平台形态、收集线索，最终抓捕「Baahd Guys」。",
      "trailerHeading": "预告片",
      "trailerNote": "游戏预告片。",
      "trailerVideoId": "caEVKftmSHA",
      "responsibilitiesHeading": "主要职责",
      "responsibilities": [
        "设计了教程关卡、第一关的后半部分，以及整个第三关和第四关，循序渐进地引入并强化游戏的核心折叠机制。",
        "在初期头脑风暴阶段提出并主导了「折叠」这一核心机制，探索其在空间移动和解谜深度上的多种应用。",
        "与团队程序员密切合作，在确定关卡布局前明确技术限制，并协助排查实现过程中的问题。",
        "在团队出现早期人际摩擦时主动促成坦诚沟通，根据每位队友的沟通风格调整自己的方式。",
        "参与 GDD/LDD 文档编写，并协助美术团队统一视觉方向。"
      ],
      "screenshotsHeading": "游戏截图",
      "screenshotsNote": "教程关卡、第三关的对角线折叠迷宫，以及第四关的恐龙遭遇战。",
      "screenshots": [
        "../images/detective-folder/shot-2.jpg",
        "../images/detective-folder/shot-3.jpg",
        "../images/detective-folder/shot-4.jpg",
        "../images/detective-folder/shot-1.jpg"
      ],
      "postmortemHeading": "项目复盘",
      "postmortem": "从最初的概念构思到贯穿四个关卡的实现，主导折叠机制的过程教会了我把失败当作数据来看待——由于这类机制没有太多现成参考，我采用了「快速失败」的方法保持高速迭代。最大的教训在于范围管理：像第四关的恐龙这样的功能虽然有趣，但成本很高，如果没有严格的资产锁定纪律，我们就会把时间花在制造视觉效果上，而不是打磨核心体验。我也学到了应该更早引入玩家测试——等我们发现玩家在新手引导上遇到困难时，已经太晚了，只能仓促重做教程关卡。归根结底，这个项目让我明白了预生产阶段的技术验证，以及清晰文档作为团队「唯一真相来源」的价值，这对于一个正在摸索全新机制的团队来说尤为重要。"
    },
    "capstone": {
      "backLink": "← 返回项目",
      "tagLabel": "CAPSTONE 毕业项目（占位）",
      "gameName": "Box Shot",
      "image": "../images/project-placeholder.svg",
      "roleLabel": "角色",
      "role": "制作人",
      "teamSizeLabel": "团队规模",
      "teamSize": "占位",
      "lengthLabel": "项目周期",
      "length": "占位",
      "platformLabel": "平台",
      "platform": "占位",
      "synopsisHeading": "游戏简介",
      "synopsis": "占位文字 — 该项目详情待补充，准备好后替换为真实简介。",
      "trailerHeading": "预告片",
      "trailerNote": "占位 — 在此嵌入游戏预告片。",
      "responsibilitiesHeading": "主要职责",
      "responsibilities": [
        "占位文字 — 列出你的具体职责与贡献。"
      ],
      "screenshotsHeading": "游戏截图",
      "screenshotsNote": "占位 — 添加游戏截图。",
      "postmortemHeading": "项目复盘",
      "postmortem": "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。"
    },
    "individualProjects": {
      "heading": "个人项目与认证",
      "intro": "独立完成的作品，包括你的 DFS（定向研究）或毕业设计项目。",
      "list": [
        {
          "id": "fire",
          "tag": "个人项目",
          "name": "芳心纵火犯",
          "blurb": "一款用团结引擎制作的 2.5D 游戏 demo，参加 Unity Game Jam 并获铜奖。",
          "href": "individual-projects/fire.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "fire": {
      "backLink": "← 返回项目",
      "tagLabel": "个人项目（占位）",
      "projectName": "芳心纵火犯",
      "image": "../images/project-placeholder.svg",
      "roleLabel": "角色",
      "role": "制作人/关卡策划",
      "teamSizeLabel": "团队规模",
      "teamSize": "占位（如：独立完成）",
      "lengthLabel": "项目周期",
      "length": "占位",
      "synopsisHeading": "项目简介",
      "synopsis": "占位文字 — 描述这个项目，即使还在进行中也没关系。",
      "trailerHeading": "预告片",
      "trailerNote": "游戏预告片。",
      "trailerVideoId": "713lnqBMnyk",
      "responsibilitiesHeading": "主要职责",
      "responsibilities": [
        "占位文字 — 列出你的具体职责与贡献。"
      ],
      "screenshotsHeading": "项目截图",
      "screenshotsNote": "占位 — 添加项目截图。",
      "postmortemHeading": "项目复盘",
      "postmortem": "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。"
    },
    "aboutPage": {
      "pageTitle": "苟阳 — 关于我",
      "heading": "关于我",
      "photoAlt": "专业形象照占位",
      "whoHeading": "我是谁、我在做什么",
      "who": "我是一名拥有多年跨领域团队管理和流程优化经验的制作人。我将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种独特的结构化方法，擅长促成创意与设计部门之间的协作，交付打磨精良、机制扎实的项目。",
      "howHeading": "我是如何走到这里的",
      "how": "占位文字 — 简短讲讲你从建筑学转向游戏制作的故事（比如是什么吸引你从建筑转向游戏）。",
      "nextHeading": "接下来想去哪里",
      "next": "占位文字 — 描述你希望加入的角色、工作室或团队类型。",
      "funHeading": "一些有趣的小事",
      "fun": "占位文字 — 一两个轻松的个人细节（爱好、最喜欢的游戏等），展现你的个性。"
    },
    "beyondWorkPage": {
      "pageTitle": "苟阳 — 游戏之外",
      "heading": "游戏之外",
      "lead": "占位文字 — 简短介绍一下工作和游戏之外的你。",
      "galleryHeading": "照片墙",
      "galleryNote": "占位 — 之后随时可以替换成真实照片。",
      "photos": [
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" },
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" },
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" },
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" },
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" },
        { "src": "images/project-placeholder.svg", "caption": "占位说明文字" }
      ],
      "sectionsHeading": "板块",
      "sectionsIntro": "不做游戏的时候，时间大概花在这四件事上。",
      "sections": [
        {
          "id": "photography",
          "tag": "摄影",
          "name": "摄影",
          "blurb": "占位文字 — 你拍什么，以及为什么一直拍下去。",
          "href": "beyond-work/photography.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "architecture",
          "tag": "建筑",
          "name": "建筑",
          "blurb": "占位文字 — 建筑背景如何影响你看待空间的方式。",
          "href": "beyond-work/architecture.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "travel",
          "tag": "旅行",
          "name": "旅行",
          "blurb": "占位文字 — 去过哪里，带回了什么。",
          "href": "beyond-work/travel.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "cooking",
          "tag": "厨艺",
          "name": "厨艺",
          "blurb": "占位文字 — 你做什么菜，做给谁吃。",
          "href": "beyond-work/cooking.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "aiToolPage": {
      "pageTitle": "苟阳 — AI Playtest 反馈工具",
      "tagLabel": "AI 演示",
      "heading": "AI Playtest 反馈归纳",
      "lead": "一个小工具，用来展示把 AI 用在真实制作流程里的实践经验：粘贴原始的 playtest 反馈，它会按制作人手工分诊的方式返回结果——拆成一条条独立条目，每条标注属于哪类工作、以及对体验的伤害有多大。",
      "disclaimer": "这个功能调用了一个由语言模型驱动的小型 serverless 函数。你粘贴的内容不会被存储，只用于生成下面的归类摘要。",
      "inputLabel": "粘贴 playtest 反馈",
      "inputPlaceholder": "把一位或多位测试者写的反馈粘贴在这里……",
      "sampleButton": "载入示例反馈",
      "sampleText": "Playtest 记录 —— 0.4.2 版本，6 名测试者，每人 45 分钟。\n\n两名测试者在 Boss 战里打开地图时直接崩溃。其中一人因为上一个存档点在竞技场之前，丢了大约 40 分钟的进度。\n三个人到第二个区域才知道有冲刺这个动作。其中两人说，应该在第一个跳不过去的缺口那里给个提示。\nBoss 二是道墙 —— 四名测试者在这里死了五次以上。有人直接说「Boss 三比 Boss 二还简单」。\n集市场景在两台笔记本上掉帧到幻灯片，台式机没问题。\n一名测试者把存档图标看成了删除按钮，整局都不敢点。\n所有人都喜欢美术。有三个人没被问就主动提到了第二关的音乐。\n两个人希望能自定义按键 —— 其中一人说跳跃放在 B 键上，玩 20 分钟手会疼，他建议在设置里加一个按键绑定界面。\n1080p 下字幕会和立绘叠在一起，不过似乎没人在意。",
      "submitButton": "分析反馈",
      "loadingLabel": "分析中…",
      "summaryHeading": "总结",
      "emptyCategoryNote": "这段反馈没有识别出可归类的内容。",
      "errorEmpty": "请先粘贴一些反馈文字。",
      "errorTooLong": "文字有点太长了，请控制在 4000 字以内。",
      "errorNotConfigured": "这个演示的后端还没有部署，请稍后再来看看。",
      "errorRequestFailed": "请求 AI 服务时出了点问题，请稍后再试一次。",
      "rateLimitNote": "为了控制托管成本，这个演示每天限制使用 {limit} 次，今天还剩 {remaining} 次。",
      "rateLimitReached": "今天这个演示的 {limit} 次额度已经用完了，明天再来试试吧。",
      "taxonomyNote": "每条反馈按两个维度分类：属于哪类工作（类型），以及对体验的伤害有多大（严重度）。类型决定这活儿归谁做，严重度和被提及的次数决定先做哪一条。",
      "priorityHeading": "优先处理",
      "mentionsLabel": "被提到 {n} 次",
      "playerFixLabel": "玩家提出的方案",
      "typeLabels": {
        "bug": "Bug",
        "performance": "性能",
        "usability": "易用性",
        "balance": "数值平衡",
        "content": "内容",
        "request": "功能需求",
        "other": "其他",
        "positive": "做对了的地方"
      },
      "severityLabels": {
        "critical": "严重",
        "major": "较重",
        "minor": "轻微",
        "unrated": "未分级"
      }
    },
    "skills": {
      "heading": "技能",
      "items": [
        "项目管理",
        "Jira",
        "敏捷开发",
        "Lark 飞书",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity"
      ],
      "languagesLabel": "语言",
      "languages": [
        "英语",
        "中文（普通话）"
      ]
    },
    "experience": {
      "heading": "工作经历",
      "items": [
        {
          "title": "系统设计实习生",
          "org": "莉莉丝游戏 (Lilith Games)",
          "location": "中国上海",
          "dates": "2025.04 — 2025.08",
          "bullets": [
            "为《AFK Arena（剑与远征）》项目设计系统，与多专业团队协作，优化大型 SLG 玩法机制以提升玩家参与度。",
            "开发并平衡新的 PvP 排位系统，与负责人及相关方沟通目标，提升竞技玩法体验。"
          ]
        },
        {
          "title": "建筑设计实习生",
          "org": "中国西南建筑设计研究院 (CSWADI)",
          "location": "中国成都",
          "dates": "2022.08 — 2022.11",
          "bullets": [
            "完成三份初步设计方案，向相关方汇报提案，深化建筑细节，并最终确定四川大学华西第二医院的立面设计，提升项目与客户愿景的契合度。"
          ]
        }
      ]
    },
    "education": {
      "heading": "教育背景",
      "items": [
        {
          "degree": "硕士：交互技术 · 数字游戏开发 — 制作方向",
          "school": "南卫理公会大学 (SMU) Guildhall",
          "location": "美国德克萨斯州达拉斯",
          "dates": "预计 2027.06 毕业"
        },
        {
          "degree": "建筑学学士",
          "school": "天津大学",
          "location": "中国天津",
          "dates": "2023.06"
        }
      ]
    },
    "blog": {
      "heading": "文章",
      "viewAll": "查看全部文章",
      "recentLabel": "最新文章",
      "viewAllPosts": "查看全部文章",
      "items": [
        {
          "slug": "lessons-from-gearbox",
          "title": "Gearbox 拜访笔记",
          "date": "日期待定",
          "category": "职业发展",
          "excerpt": "一次 Gearbox 工作室拜访的笔记——聊反馈、沟通，以及制作人工作的本质。",
          "pullQuote": "友谊铸就上线——但这不代表什么都要替他们做。",
          "body": [
            "上周我们见了 Gearbox 的执行制作人 J. Low，以及制作助理总监 Lou。",
            "他们都身处“高层”位置，给我的第一印象是，他们的沟通方式和之前接触过的制作人很不一样——非常直接，几乎没有一句废话。这让我开始反思，自己是不是有时候只是“为了沟通而沟通”，说得多并不代表沟通得好。除了口头表达，他们两位都会用手绘的方式更准确地传达想法，这让我想起做建筑师时，我们也常用手绘和客户沟通。已经很久没再用这个方法了，具体为什么停下来的我也记不清，但我觉得是时候把它重新捡回来，当作沟通的“武器”。",
            "我们聊了很多关于职业发展的话题。",
            "怎么接受反馈？J. Low 说每个人都有自己的盲区，要多想“我没看到的是什么”，对反馈保持开放，尤其是那些来自你不太合得来的人的反馈，往往最有价值。收到反馈后，要想清楚背后的原因：如果是负面反馈——为什么？它是建设性的吗？我该怎么改？如果还是不理解，就直接去找对方聊。",
            "怎么给反馈？直接、有建设性。Lou 说完全不需要用“表扬三明治”的方式，这一点我很认同。但直接不代表刻薄，我还是会带着对对方贡献的认可去给反馈。",
            "Lou 还提到了“能力四阶段”：无意识的不胜任、有意识的不胜任、有意识的胜任、无意识的胜任。我们其实一直在这个循环里打转。",
            "Lou 也聊到了职业生涯中的“共情转变”，说实话我现在还不太清楚该怎么应对，但我猜等真正进入行业后会更有体会。",
            "制作人的工作到底是什么？这是我们讨论的另一个大问题。一句话总结：“维持住势头（momentum）”。很多新人制作人最容易掉进的一个陷阱，是对团队或组长投入过多情绪。“友谊铸就上线（Friendship leads to ship）”，但这不代表什么都要替他们做。学会给自己的工作做取舍很关键，因为每次晋升，工作本身都会变。",
            "最后是一些简历方面的建议：不放照片、不要用 AI 写求职信、多用强动词（比如“我推动了…”），少用被动表达（比如“我参与了…”）。这一条对我触动很大。"
          ]
        },
        {
          "title": "占位文章标题",
          "date": "日期",
          "category": "设计"
        },
        {
          "title": "占位文章标题",
          "date": "日期",
          "category": "复盘"
        }
      ]
    },
    "personalProjects": {
      "heading": "个人作品",
      "intro": "占位文字 — 课余/工作之外的个人项目、游戏 Jam 或探索性作品。",
      "items": [
        {
          "title": "占位项目",
          "blurb": "占位文字 — 简短描述。",
          "href": "#"
        }
      ]
    },
    "contact": {
      "heading": "联系方式",
      "lead": "欢迎聊聊游戏、团队或合作机会。",
      "locationLabel": "所在地",
      "location": "美国德州达拉斯（留学中）",
      "emailLabel": "邮箱",
      "email": "younago@foxmail.com",
      "websiteLabel": "微信",
      "website": "younago920"
    },
    "footer": {
      "note": "用心打造，保留所有权利。"
    },
    "resumePage": {
      "pageTitle": "苟阳 — 简历",
      "title": "简历",
      "roleTag": "游戏制作人",
      "downloadPdf": "下载 简历",
      "backHome": "← 返回主页",
      "embedHeading": "简历内嵌预览（PDF）",
      "embedNote": "已根据你的简历草稿生成。之后若有新版本，直接替换项目里的 ZhongyinGou_resume.pdf 文件即可自动更新这里的预览。",
      "summaryHeading": "简介",
      "summary": "拥有多年跨领域团队管理和流程优化经验的制作人。将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种独特的结构化方法。",
      "contactHeading": "联系方式",
      "experienceHeading": "工作经历",
      "educationHeading": "教育背景",
      "skillsHeading": "技能",
      "projectsHeading": "代表项目"
    },
    "gameAnalysis": {
      "heading": "游戏分析",
      "intro": "拆解那些我反复回去玩的游戏——系统、经济与关卡节奏。",
      "list": [
        {
          "id": "analysis-1",
          "tag": "分析 · 待定",
          "name": "分析一 — 标题待定",
          "blurb": "占位文字 — 一句话说明拆的是哪款游戏、结论是什么。",
          "href": "game-analysis/analysis-1.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "analysis-2",
          "tag": "分析 · 待定",
          "name": "分析二 — 标题待定",
          "blurb": "占位文字 — 一句话说明拆的是哪款游戏、结论是什么。",
          "href": "game-analysis/analysis-2.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "analysis-3",
          "tag": "分析 · 待定",
          "name": "分析三 — 标题待定",
          "blurb": "占位文字 — 一句话说明拆的是哪款游戏、结论是什么。",
          "href": "game-analysis/analysis-3.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ]
    },
    "aiHubPage": {
      "pageTitle": "苟阳 — AI",
      "tagLabel": "AI",
      "heading": "AI 相关",
      "lead": "用 AI 做的小实验和能直接用的工具——点开任意一个查看。",
      "projectsHeading": "AI 小项目",
      "projectsIntro": "为了回答某个问题而做的原型和实验。",
      "projects": [
        {
          "id": "ai-project-1",
          "tag": "小项目 · 待定",
          "name": "AI 小项目一 — 标题待定",
          "blurb": "占位文字 — 一句话说明它做什么、你学到了什么。",
          "href": "ai-projects/project-1.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        },
        {
          "id": "ai-project-2",
          "tag": "小项目 · 待定",
          "name": "AI 小项目二 — 标题待定",
          "blurb": "占位文字 — 一句话说明它做什么、你学到了什么。",
          "href": "ai-projects/project-2.html",
          "image": "images/project-placeholder.svg",
          "placeholder": true
        }
      ],
      "toolsHeading": "AI 工具",
      "toolsIntro": "可以在浏览器里直接跑起来的工具。",
      "tools": [
        {
          "id": "playtest",
          "tag": "可直接使用",
          "name": "Playtest 反馈归纳器",
          "blurb": "粘贴原始 playtest 反馈，AI 自动归纳成分类主题。",
          "href": "ai-tools/playtest-feedback.html",
          "image": "images/project-placeholder.svg",
          "placeholder": false
        },
        {
          "id": "reffix",
          "tag": "可直接使用",
          "name": "RefFix — 参考文献格式化",
          "blurb": "把参考文献列表一键整理成 IEEE / APA 7 / MLA 9 格式。以规则集为主，规则覆盖不到的地方才交给 AI 判断，全程在浏览器本地运行。",
          "href": "ai-tools/reffix.html",
          "image": "images/reffix-cover.svg",
          "placeholder": false
        }
      ]
    },
    "stories": {
      "photography": {
        "pageTitle": "苟阳 — 摄影",
        "tagLabel": "摄影",
        "heading": "摄影",
        "lead": "占位文字 — 怎么开始拍照的，以及你在找什么。",
        "backLink": "← 返回游戏之外",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "architecture": {
        "pageTitle": "苟阳 — 建筑",
        "tagLabel": "建筑",
        "heading": "建筑",
        "lead": "占位文字 — 建筑背景如何影响你阅读空间的方式。",
        "backLink": "← 返回游戏之外",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "travel": {
        "pageTitle": "苟阳 — 旅行",
        "tagLabel": "旅行",
        "heading": "旅行",
        "lead": "占位文字 — 去过哪些地方，留下了什么。",
        "backLink": "← 返回游戏之外",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "cooking": {
        "pageTitle": "苟阳 — 厨艺",
        "tagLabel": "厨艺",
        "heading": "厨艺",
        "lead": "占位文字 — 你做什么菜，做饭和做项目有什么共通之处。",
        "backLink": "← 返回游戏之外",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "analysis-1": {
        "pageTitle": "苟阳 — 游戏分析",
        "tagLabel": "分析 · 待定",
        "heading": "分析一 — 标题待定",
        "lead": "占位文字 — 拆的是哪款游戏，想回答什么问题。",
        "backLink": "← 返回项目",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "analysis-2": {
        "pageTitle": "苟阳 — 游戏分析",
        "tagLabel": "分析 · 待定",
        "heading": "分析二 — 标题待定",
        "lead": "占位文字 — 拆的是哪款游戏，想回答什么问题。",
        "backLink": "← 返回项目",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "analysis-3": {
        "pageTitle": "苟阳 — 游戏分析",
        "tagLabel": "分析 · 待定",
        "heading": "分析三 — 标题待定",
        "lead": "占位文字 — 拆的是哪款游戏，想回答什么问题。",
        "backLink": "← 返回项目",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "ai-project-1": {
        "pageTitle": "苟阳 — AI 小项目",
        "tagLabel": "小项目 · 待定",
        "heading": "AI 小项目一 — 标题待定",
        "lead": "占位文字 — 你做了什么，为什么做。",
        "backLink": "← 返回 AI",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "ai-project-2": {
        "pageTitle": "苟阳 — AI 小项目",
        "tagLabel": "小项目 · 待定",
        "heading": "AI 小项目二 — 标题待定",
        "lead": "占位文字 — 你做了什么，为什么做。",
        "backLink": "← 返回 AI",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      },
      "tool-2": {
        "pageTitle": "苟阳 — AI 工具",
        "tagLabel": "工具 · 待定",
        "heading": "工具二 — 标题待定",
        "lead": "占位文字 — 这个工具建成后会做什么。",
        "backLink": "← 返回 AI",
        "blocks": [
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          },
          {
            "heading": "占位小标题",
            "text": "占位文字 — 换成真实内容。配图旁边写两三句话最合适。",
            "image": "images/project-placeholder.svg",
            "caption": "占位图说"
          }
        ]
      }
    },
    "reffixPage": {
      "pageTitle": "苟阳 — RefFix",
      "tagLabel": "可直接使用 · 开源",
      "heading": "RefFix",
      "lead": "我做的一个工具，把学术参考文献列表整理成 IEEE / APA 7 / MLA 9 格式——同时如实说明哪些它修不了。",
      "backLink": "← 返回 AI",
      "whyHeading": "为什么做",
      "why": "参考文献格式是纯机械劳动，却总在交稿前吃掉一个晚上；而且这类错误别人一眼就能看出来，写的人改到第四遍反而看不见了。它正好符合值得自动化的特征：量大、判断少、而且有公开的格式规范可依。",
      "howHeading": "怎么做的",
      "how": "绝大部分工作由确定性的规则集完成——先把每条文献拆成字段，再按目标格式重新渲染。只有在规则真正覆盖不到的地方才交给 AI：格式残缺、有歧义、或者用了解析器不认识的写法的条目。先规则、后模型，因为规则错了是一个可以一次性修掉的 bug，模型错了则是每次都可能出现的意外。",
      "principleHeading": "唯一不破的原则",
      "principle": "绝不编造文献信息。缺 DOI、缺页码、缺出版社时，工具会把这条标记出来，而不是填一个看起来合理的值——一条编造的引用比一条没排好版的引用糟糕得多。",
      "privacyHeading": "跑在哪里",
      "privacy": "整条 Python 处理流程通过 Pyodide 跑在浏览器里，没有后端。你拖进去的文档不会离开你的设备；顺带的好处是托管成本为零，即使哪天我不再维护服务端，它也照样能用。",
      "openLabel": "打开完整版",
      "repoLabel": "GitHub 源码",
      "embedNote": "下面直接嵌入了真实工具。它也可以独立打开——想要完整窗口就点上面的按钮。",
      "embedUrl": "https://younago.github.io/IEEE-Format-Correct/",
      "repoUrl": "https://github.com/Younago/IEEE-Format-Correct"
    }
  }
};

// Expose for other scripts (plain <script> tags, no bundler)
window.SITE_CONTENT = SITE_CONTENT;
