// ---------------------------------------------------------------------------
// All editable site copy lives here, in English and Chinese.
// Replace placeholder strings/images with real content whenever it's ready —
// the rendering logic in the page scripts does not need to change.
// ---------------------------------------------------------------------------

const SITE_CONTENT = {
  en: {
    nav: {
      home: "HOME",
      about: "ABOUT",
      projects: "PROJECTS",
      experience: "EXPERIENCE",
      education: "EDUCATION",
      writing: "WRITING",
      contact: "CONTACT",
      aboutFull: "ABOUT ME",
      resume: "RESUME",
    },
    site: { name: "YOUNG GOU" },

    hero: {
      eyebrow: "Strength in Numbers",
      name: "YOUNG GOU",
      nameLines: ["YOUNG", "GOU"],
      portrait: "images/portrait.jpg",
      photoCaption: "Dallas, TX",
      workPhotos: ["images/work/work-1.jpg", "images/work/work-2.jpg", "images/work/work-3.jpg"],
      intro:
        "I'm Young Gou — a producer with several years of experience managing multidisciplinary teams and optimization pipelines. I fuse a background in architecture with expertise in game systems design to bring a structural approach to project logistics, scope management, and cross-departmental communication.",
      scroll: "SCROLL",
    },

    home: {
      teamProjectsHeading: "Team Projects",
      resumeCard: { title: "Resume", body: "Full work history, skills, and education.", cta: "View resume →" },
      aboutCard: { title: "About Me", body: "Who I am, how I got here, and what's next.", cta: "Read more →" },
      contactHeading: "Contact",
    },

    // ---- On-page About / Projects preview (single-page overview) -----------
    about: {
      heading: "About",
      lead: "My passion lies in game production, leading diverse cross-disciplinary teams to create fantastic games.",
      body: "Producer with several years of experience managing multidisciplinary teams and optimization pipelines. I fuse a background in architecture with expertise in game systems design to bring a structural approach to project logistics, scope management, and cross-departmental communication.",
      readMore: "Read the full story →",
      readMoreHref: "about.html",
      skills: [
        "Project Management",
        "Jira",
        "Agile",
        "Lark",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity",
      ],
    },
    projects: {
      heading: "Projects",
      relatedHeading: "Related Projects",
      items: [
        { title: "Hamsterballin'", tag: "TEAM GAME PROJECT 2", role: "Producer", summary: "A fast-paced racing game built in Unreal Engine 5, on Steam.", href: "team-projects/tgp2.html", image: "images/hamsterballin-card.jpg", placeholder: false },
        { title: "Detective Folder", tag: "TEAM GAME PROJECT 1", role: "Level Designer", summary: "A 2D puzzle-platformer where a detective folds a living comic-book world to gather clues and catch the \"Baahd Guys.\"", href: "team-projects/tgp1.html", image: "images/detective-folder-card.jpg", placeholder: false },
        { title: "Box Shot", tag: "CAPSTONE", role: "Placeholder role", summary: "Placeholder — one or two sentences on what the game is and what you contributed.", href: "team-projects/capstone.html", image: "images/project-placeholder.svg", placeholder: true },
        { title: "Fire", tag: "INDIVIDUAL", role: "Placeholder role", summary: "Placeholder — one or two sentences on what the game is and what you contributed.", href: "individual-projects/fire.html", image: "images/project-placeholder.svg", placeholder: true },
      ],
    },

    // ---- Team Projects -----------------------------------------------------
    teamProjects: {
      heading: "Team Projects",
      intro: "Game projects built with cross-functional student and studio teams.",
      list: [
        {
          id: "tgp2",
          tag: "TEAM GAME PROJECT 2",
          name: "Hamsterballin'",
          role: "Producer",
          teamSize: "43",
          length: "1 semester",
          blurb: "A fast-paced racing game built in Unreal Engine 5, on Steam.",
          href: "team-projects/tgp2.html",
          image: "../images/hamsterballin-card.jpg",
          placeholder: false,
        },
        {
          id: "tgp1",
          tag: "TEAM GAME PROJECT 1",
          name: "Detective Folder",
          role: "Level Designer",
          teamSize: "5",
          length: "1 semester",
          blurb: "A 2D puzzle-platformer built in Unity where a detective folds a living comic-book world to catch the \"Baahd Guys.\"",
          href: "team-projects/tgp1.html",
          image: "../images/detective-folder-card.jpg",
          placeholder: false,
        },
        {
          id: "capstone",
          tag: "CAPSTONE",
          name: "Box Shot",
          role: "Placeholder role",
          teamSize: "Placeholder",
          length: "Placeholder",
          blurb: "Placeholder — one-line description of the game.",
          href: "team-projects/capstone.html",
          image: "../images/project-placeholder.svg",
          placeholder: true,
        },
      ],
    },
    tgp2: {
      backLink: "← Back to Team Projects",
      tagLabel: "TEAM GAME PROJECT 2",
      gameName: "Hamsterballin'",
      image: "../images/hamsterballin-hero.jpg",
      roleLabel: "Role",
      role: "Producer",
      teamSizeLabel: "Team Size",
      teamSize: "43",
      lengthLabel: "Length",
      length: "1 semester",
      platformLabel: "Platform",
      platform: "PC (Steam) — Unreal Engine 5",
      synopsisHeading: "Synopsis",
      synopsis:
        "Hamsterballin' is a fast-paced racing game built in Unreal Engine 5 by a 43-person cross-functional student team of designers, artists, and programmers, released on Steam.",
      trailerHeading: "Trailer",
      trailerNote: "Placeholder — embed the game trailer here.",
      responsibilitiesHeading: "Responsibilities",
      responsibilities: [
        "Led a 43-person cross-functional team of designers, artists, and programmers through the full development cycle.",
        "Facilitated Agile/Scrum methodologies for a large-scale student team — sprint planning, daily stand-ups, and retrospectives — to ensure timely milestone deliveries.",
        "Managed project schedules and task tracking to mitigate scope creep and resolve development bottlenecks across multiple disciplines.",
        "Coordinated regular playtesting sessions, synthesizing player feedback to guide iterative design improvements and performance optimizations.",
      ],
      screenshotsHeading: "Screenshots",
      screenshotsNote: "Placeholder — add gameplay screenshots.",
      postmortemHeading: "Postmortem",
      postmortem: "Placeholder — reflect on what went well, what you'd do differently, and what you learned.",
    },
    tgp1: {
      backLink: "← Back to Team Projects",
      tagLabel: "TEAM GAME PROJECT 1",
      gameName: "Detective Folder",
      image: "../images/detective-folder-hero.jpg",
      roleLabel: "Role",
      role: "Level Designer",
      teamSizeLabel: "Team Size",
      teamSize: "5",
      lengthLabel: "Length",
      length: "1 semester",
      platformLabel: "Platform",
      platform: "PC — Unity (SMU Guildhall)",
      synopsisHeading: "Synopsis",
      synopsis:
        "Detective Folder is a 2D puzzle-platformer built in Unity by a 5-person student team, in which you play a detective for the clandestine Anomalous Crimes Unit — folding a living comic-book world to reshape platforms, uncover clues, and track down the \"Baahd Guys.\"",
      trailerHeading: "Trailer",
      trailerNote: "Gameplay trailer.",
      trailerVideoId: "caEVKftmSHA",
      responsibilitiesHeading: "Responsibilities",
      responsibilities: [
        "Designed the Tutorial level, the second half of Level 1, and all of Level 3 and Level 4, systematically introducing and reinforcing the game's core folding mechanic.",
        "Proposed and took ownership of the \"folding\" mechanic during initial brainstorming, exploring its use for both spatial navigation and puzzle depth across the game.",
        "Worked directly with the team's programmer to establish technical constraints before committing to level layouts, and helped troubleshoot implementation issues.",
        "Facilitated open, honest communication within the team to resolve early interpersonal friction, adapting my approach to each teammate's working style.",
        "Contributed to the GDD/LDD documentation and helped the art team align on visual direction.",
      ],
      screenshotsHeading: "Screenshots",
      screenshotsNote: "Tutorial, Level 3's diagonal-folding maze, and Level 4's dinosaur encounters.",
      screenshots: [
        "../images/detective-folder/shot-2.jpg",
        "../images/detective-folder/shot-3.jpg",
        "../images/detective-folder/shot-4.jpg",
        "../images/detective-folder/shot-1.jpg",
      ],
      postmortemHeading: "Postmortem",
      postmortem:
        "Owning the folding mechanic from initial concept through four levels taught me to treat failure as data — with no existing reference for this kind of mechanic, I leaned on a \"fail fast\" approach to keep iterating at speed. The biggest lesson was around scope: features like Level 4's dinosaurs were fun but expensive, and without rigorous asset-lock discipline we spent time on spectacle instead of polish. I also learned to bring in playtesters earlier — by the time we saw players struggle with onboarding, it was late enough that we had to scramble to rebuild the tutorial. Above all, this project taught me the value of pre-production technical validation and clear documentation as a single source of truth for a team working through a genuinely novel mechanic.",
    },
    capstone: {
      backLink: "← Back to Team Projects",
      tagLabel: "CAPSTONE PROJECT (PLACEHOLDER)",
      gameName: "Box Shot",
      image: "../images/project-placeholder.svg",
      roleLabel: "Role",
      role: "Placeholder",
      teamSizeLabel: "Team Size",
      teamSize: "Placeholder",
      lengthLabel: "Length",
      length: "Placeholder",
      platformLabel: "Platform",
      platform: "Placeholder",
      synopsisHeading: "Synopsis",
      synopsis: "Placeholder — this project's details are pending. Replace with a real synopsis when ready.",
      trailerHeading: "Trailer",
      trailerNote: "Placeholder — embed the game trailer here.",
      responsibilitiesHeading: "Responsibilities",
      responsibilities: ["Placeholder — list your specific responsibilities and contributions."],
      screenshotsHeading: "Screenshots",
      screenshotsNote: "Placeholder — add gameplay screenshots.",
      postmortemHeading: "Postmortem",
      postmortem: "Placeholder — reflect on what went well, what you'd do differently, and what you learned.",
    },

    // ---- Individual Projects / Certifications ------------------------------
    individualProjects: {
      heading: "Individual Projects & Certifications",
      intro: "Independent work, including your Directed Focus Study (DFS) or thesis project.",
      list: [
        {
          id: "fire",
          tag: "INDIVIDUAL PROJECT",
          name: "Fire",
          blurb: "Placeholder — one-line description. Work-in-progress projects are welcome here.",
          href: "individual-projects/fire.html",
          image: "../images/project-placeholder.svg",
          placeholder: true,
        },
      ],
    },
    fire: {
      backLink: "← Back to Individual Projects",
      tagLabel: "INDIVIDUAL PROJECT (PLACEHOLDER)",
      projectName: "Fire",
      image: "../images/project-placeholder.svg",
      roleLabel: "Role",
      role: "Placeholder",
      teamSizeLabel: "Team Size",
      teamSize: "Placeholder (e.g. Solo)",
      lengthLabel: "Length",
      length: "Placeholder",
      synopsisHeading: "Synopsis",
      synopsis: "Placeholder — describe the project, even if it's a work in progress.",
      responsibilitiesHeading: "Responsibilities",
      responsibilities: ["Placeholder — list your specific responsibilities and contributions."],
      screenshotsHeading: "Screenshots",
      screenshotsNote: "Placeholder — add project screenshots.",
      postmortemHeading: "Postmortem",
      postmortem: "Placeholder — reflect on what went well, what you'd do differently, and what you learned.",
    },

    // ---- About Me -----------------------------------------------------------
    aboutPage: {
      pageTitle: "Young Gou — About Me",
      heading: "About Me",
      photoAlt: "Professional portrait placeholder",
      whoHeading: "Who I am & what I'm doing",
      who: "Producer with several years of experience managing multidisciplinary teams and optimization pipelines. I fuse a background in architecture with expertise in game systems design to bring a unique, structural approach to project logistics, scope management, and cross-departmental communication. Highly skilled at facilitating alignment between creative and design disciplines to deliver polished, mechanically sound projects.",
      howHeading: "How I got here",
      how: "Placeholder — a short narrative connecting your architecture background to your move into game production (e.g. what drew you from buildings to games).",
      nextHeading: "Where I'm looking to go next",
      next: "Placeholder — describe the kind of role, studio, or team you're hoping to join next.",
      funHeading: "A few fun facts",
      fun: "Placeholder — a couple of light, personal details (hobbies, favorite games, etc.) that show your voice.",
    },

    // ---- Skills / Experience / Education (feeds Resume + About) ------------
    skills: {
      heading: "Skills",
      items: [
        "Project Management",
        "Jira",
        "Agile",
        "Lark",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity",
      ],
      languagesLabel: "Languages",
      languages: ["English", "Chinese (Mandarin)"],
    },
    experience: {
      heading: "Experience",
      items: [
        {
          title: "Systems Designer Intern",
          org: "Lilith Games",
          location: "Shanghai, China",
          dates: "04/2025 — 08/2025",
          bullets: [
            "Designed systems for the AFK Arena project, working with multidiscipline teams, enhancing large-scale, in-game SLG mechanics for improved player engagement.",
            "Developed and balanced a new PvP ranking system by communicating with leads and others to meet their goals, aiming to elevate the competitive gameplay experience.",
          ],
        },
        {
          title: "Architectural Intern",
          org: "China Southwest Architectural Design and Research Institute (CSWADI)",
          location: "Chengdu, China",
          dates: "08/2022 — 11/2022",
          bullets: [
            "Developed three preliminary design proposals, presented pitches to stakeholders, refined architectural details, and finalized the facade design for the Second University Hospital of West China, improving project alignment with client vision.",
          ],
        },
      ],
    },
    education: {
      heading: "Education",
      items: [
        {
          degree: "Master's: Interactive Technology, Digital Game Development — Production Track",
          school: "Southern Methodist University (SMU) Guildhall",
          location: "Dallas, TX, USA",
          dates: "Expected 06/2027",
        },
        {
          degree: "Bachelor of Architecture",
          school: "Tianjin University",
          location: "Tianjin, China",
          dates: "06/2023",
        },
      ],
    },

    blog: {
      heading: "Writing",
      viewAll: "View all writing →",
      recentLabel: "Recent Posts",
      viewAllPosts: "View all posts →",
      items: [
        {
          slug: "lessons-from-gearbox",
          title: "Lessons from Gearbox",
          date: "Date TBD",
          category: "Career",
          excerpt:
            "Notes from a studio visit with Gearbox's EP and assistant director of production — on feedback, communication, and what a producer's job really is.",
          pullQuote: "Friendship leads to ship — but it doesn't mean we have to do everything for them.",
          body: [
            "Last week we met with J. Low, the executive producer, and Lou, the assistant director of production.",
            "Both of them hold “high-level” positions, and the first impression was how different their communication style is from producers I've met before — very straightforward, with almost no wasted words. It made me think about whether I sometimes communicate just for the sake of communicating; speaking more doesn't necessarily make me a better communicator. Beyond talking, they both used hand-drawing to make their points clearer, which reminded me of my time as an architect, when we used hand-drawing to communicate with clients. It's been a long time since I stopped — I don't even remember why — but I think it's worth picking back up as a “weapon” for communication.",
            "We talked a lot about career development.",
            "How to take feedback? J. Low said everyone has blind spots — think about “what am I not seeing,” and stay open to feedback, especially from people you don't naturally get along with. Once you get feedback, think about the reason behind it: if it's negative, why? Is it constructive? How can I change? If I still don't understand, go talk to that person directly.",
            "How to give feedback? Be direct and constructive. Lou said there's no need for the “compliment sandwich,” which I found genuinely useful. But being direct doesn't mean being harsh — I still try to give feedback with appreciation for the other person's contribution.",
            "Lou also mentioned the four stages of competence: unconscious incompetence, conscious incompetence, conscious competence, and unconscious competence. We're always somewhere on that loop.",
            "Lou also talked about the “empathy shift” over the course of a career. Honestly, I'm not sure yet what to do with that, but I assume it'll matter more once I'm actually in the industry.",
            "What is a producer's job, really? That was the other big question we discussed. TL;DR: “maintain the momentum.” One of the biggest traps junior producers fall into is over-investing emotionally in their team or leads. “Friendship leads to ship” — but that doesn't mean doing everything for them. Learning to scale your work is essential, because the job itself changes with every promotion.",
            "Last but not least — resume tips: no photo, no AI-written cover letters, and use strong, active language (“I drove...”) instead of passive phrasing (“I was participating in...”). That one really landed for me.",
          ],
        },
        { title: "Placeholder article title", date: "Date", category: "Design" },
        { title: "Placeholder article title", date: "Date", category: "Postmortem" },
      ],
    },
    personalProjects: {
      heading: "Personal Projects",
      intro: "Placeholder — side projects, game jams, or explorations outside of school/work.",
      items: [{ title: "Placeholder project", blurb: "Placeholder — short description.", href: "#" }],
    },

    contact: {
      heading: "Contact",
      lead: "Let's talk about games, teams, or opportunities.",
      locationLabel: "Location",
      location: "Dallas, TX 75206",
      emailLabel: "Email",
      email: "younago@foxmail.com",
      websiteLabel: "Website",
      website: "www.gogo.fyi",
    },
    footer: {
      note: "Built with care. All rights reserved.",
    },
    resumePage: {
      pageTitle: "Young Gou — Resume",
      title: "Resume",
      roleTag: "Game Producer",
      downloadPdf: "Download PDF",
      backHome: "← Back to site",
      embedHeading: "Embedded Resume (PDF)",
      embedNote: "Generated from your resume draft. Replace resume.pdf with a newer export any time and this preview updates automatically.",
      summaryHeading: "Summary",
      summary:
        "Producer with several years of experience managing multidisciplinary teams and optimization pipelines. Fuses a background in architecture with expertise in game systems design to bring a unique, structural approach to project logistics, scope management, and cross-departmental communication.",
      contactHeading: "Contact",
      experienceHeading: "Experience",
      educationHeading: "Education",
      skillsHeading: "Skills",
      projectsHeading: "Selected Projects",
    },
  },

  zh: {
    nav: {
      home: "首页",
      about: "关于我",
      projects: "项目作品",
      experience: "工作经历",
      education: "教育背景",
      writing: "文章",
      contact: "联系方式",
      aboutFull: "关于我（详情）",
      resume: "简历",
    },
    site: { name: "苟阳" },

    hero: {
      eyebrow: "众多之力",
      name: "苟阳",
      nameLines: ["YOUNG", "GOU"],
      portrait: "images/portrait.jpg",
      photoCaption: "美国达拉斯",
      workPhotos: ["images/work/work-1.jpg", "images/work/work-2.jpg", "images/work/work-3.jpg"],
      intro:
        "我是苟阳（Young Gou）——一名拥有多年跨领域团队管理和流程优化经验的制作人。我将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种结构化的方法。",
      scroll: "向下滚动",
    },

    home: {
      teamProjectsHeading: "团队项目",
      resumeCard: { title: "简历", body: "完整的工作经历、技能与教育背景。", cta: "查看简历 →" },
      aboutCard: { title: "关于我", body: "我是谁、我如何走到这里，以及接下来的方向。", cta: "了解更多 →" },
      contactHeading: "联系方式",
    },

    about: {
      heading: "关于我",
      lead: "我的热情在于游戏制作，带领多元的跨领域团队打造出色的游戏。",
      body: "我是一名拥有多年跨领域团队管理和流程优化经验的制作人。我将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种结构化的方法。",
      readMore: "查看完整介绍 →",
      readMoreHref: "about.html",
      skills: [
        "项目管理",
        "Jira",
        "敏捷开发",
        "Lark 飞书",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity",
      ],
    },
    projects: {
      heading: "项目作品",
      relatedHeading: "相关项目",
      items: [
        { title: "Hamsterballin'", tag: "TEAM GAME PROJECT 2", role: "制作人", summary: "一款用 Unreal Engine 5 制作的快节奏竞速游戏，已上线 Steam。", href: "team-projects/tgp2.html", image: "images/hamsterballin-card.jpg", placeholder: false },
        { title: "Detective Folder", tag: "TEAM GAME PROJECT 1", role: "关卡设计师", summary: "一款 2D 解谜平台游戏，玩家扮演侦探折叠一个活生生的漫画世界，收集线索并抓捕「Baahd Guys」。", href: "team-projects/tgp1.html", image: "images/detective-folder-card.jpg", placeholder: false },
        { title: "Box Shot", tag: "CAPSTONE", role: "占位角色", summary: "占位文字 — 一两句话介绍这款游戏和你的具体贡献。", href: "team-projects/capstone.html", image: "images/project-placeholder.svg", placeholder: true },
        { title: "Fire", tag: "INDIVIDUAL", role: "占位角色", summary: "占位文字 — 一两句话介绍这款游戏和你的具体贡献。", href: "individual-projects/fire.html", image: "images/project-placeholder.svg", placeholder: true },
      ],
    },

    teamProjects: {
      heading: "团队项目",
      intro: "与跨职能的学生团队及工作室团队共同完成的游戏项目。",
      list: [
        {
          id: "tgp2",
          tag: "TEAM GAME PROJECT 2",
          name: "Hamsterballin'",
          role: "制作人",
          teamSize: "43",
          length: "1 学期",
          blurb: "一款用 Unreal Engine 5 制作的快节奏竞速游戏，已上线 Steam。",
          href: "team-projects/tgp2.html",
          image: "../images/hamsterballin-card.jpg",
          placeholder: false,
        },
        {
          id: "tgp1",
          tag: "TEAM GAME PROJECT 1",
          name: "Detective Folder",
          role: "关卡设计师",
          teamSize: "5",
          length: "1 学期",
          blurb: "一款用 Unity 制作的 2D 解谜平台游戏，玩家折叠漫画世界来抓捕「Baahd Guys」。",
          href: "team-projects/tgp1.html",
          image: "../images/detective-folder-card.jpg",
          placeholder: false,
        },
        {
          id: "capstone",
          tag: "CAPSTONE",
          name: "Box Shot",
          role: "占位角色",
          teamSize: "占位",
          length: "占位",
          blurb: "占位文字 — 一句话介绍这款游戏。",
          href: "team-projects/capstone.html",
          image: "../images/project-placeholder.svg",
          placeholder: true,
        },
      ],
    },
    tgp2: {
      backLink: "← 返回团队项目",
      tagLabel: "团队游戏项目 2",
      gameName: "Hamsterballin'",
      image: "../images/hamsterballin-hero.jpg",
      roleLabel: "角色",
      role: "制作人",
      teamSizeLabel: "团队规模",
      teamSize: "43 人",
      lengthLabel: "项目周期",
      length: "1 学期",
      platformLabel: "平台",
      platform: "PC（Steam）— Unreal Engine 5",
      synopsisHeading: "游戏简介",
      synopsis:
        "Hamsterballin' 是一款用 Unreal Engine 5 制作的快节奏竞速游戏，由一支 43 人的跨职能学生团队（设计、美术、程序）共同完成，已上线 Steam。",
      trailerHeading: "预告片",
      trailerNote: "占位 — 在此嵌入游戏预告片。",
      responsibilitiesHeading: "主要职责",
      responsibilities: [
        "带领一支由设计师、美术和程序员组成的 43 人跨职能团队，完成了完整的开发周期。",
        "为大规模学生团队推行 Agile/Scrum 方法论——冲刺规划、每日站会与复盘——确保各里程碑按时交付。",
        "管理项目进度与任务追踪，控制范围蔓延，解决跨多个专业方向的开发瓶颈。",
        "统筹定期的玩家测试环节，综合玩家反馈以指导迭代设计改进与性能优化。",
      ],
      screenshotsHeading: "游戏截图",
      screenshotsNote: "占位 — 添加游戏截图。",
      postmortemHeading: "项目复盘",
      postmortem: "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。",
    },
    tgp1: {
      backLink: "← 返回团队项目",
      tagLabel: "团队游戏项目 1",
      gameName: "Detective Folder",
      image: "../images/detective-folder-hero.jpg",
      roleLabel: "角色",
      role: "关卡设计师",
      teamSizeLabel: "团队规模",
      teamSize: "5 人",
      lengthLabel: "项目周期",
      length: "1 学期",
      platformLabel: "平台",
      platform: "PC — Unity（SMU Guildhall）",
      synopsisHeading: "游戏简介",
      synopsis:
        "Detective Folder 是一款由 5 人学生团队用 Unity 制作的 2D 解谜平台游戏。玩家扮演神秘「异常犯罪调查组」的侦探，通过折叠这个如漫画书般鲜活的世界来改变平台形态、收集线索，最终抓捕「Baahd Guys」。",
      trailerHeading: "预告片",
      trailerNote: "游戏预告片。",
      trailerVideoId: "caEVKftmSHA",
      responsibilitiesHeading: "主要职责",
      responsibilities: [
        "设计了教程关卡、第一关的后半部分，以及整个第三关和第四关，循序渐进地引入并强化游戏的核心折叠机制。",
        "在初期头脑风暴阶段提出并主导了「折叠」这一核心机制，探索其在空间移动和解谜深度上的多种应用。",
        "与团队程序员密切合作，在确定关卡布局前明确技术限制，并协助排查实现过程中的问题。",
        "在团队出现早期人际摩擦时主动促成坦诚沟通，根据每位队友的沟通风格调整自己的方式。",
        "参与 GDD/LDD 文档编写，并协助美术团队统一视觉方向。",
      ],
      screenshotsHeading: "游戏截图",
      screenshotsNote: "教程关卡、第三关的对角线折叠迷宫，以及第四关的恐龙遭遇战。",
      screenshots: [
        "../images/detective-folder/shot-2.jpg",
        "../images/detective-folder/shot-3.jpg",
        "../images/detective-folder/shot-4.jpg",
        "../images/detective-folder/shot-1.jpg",
      ],
      postmortemHeading: "项目复盘",
      postmortem:
        "从最初的概念构思到贯穿四个关卡的实现，主导折叠机制的过程教会了我把失败当作数据来看待——由于这类机制没有太多现成参考，我采用了「快速失败」的方法保持高速迭代。最大的教训在于范围管理：像第四关的恐龙这样的功能虽然有趣，但成本很高，如果没有严格的资产锁定纪律，我们就会把时间花在制造视觉效果上，而不是打磨核心体验。我也学到了应该更早引入玩家测试——等我们发现玩家在新手引导上遇到困难时，已经太晚了，只能仓促重做教程关卡。归根结底，这个项目让我明白了预生产阶段的技术验证，以及清晰文档作为团队「唯一真相来源」的价值，这对于一个正在摸索全新机制的团队来说尤为重要。",
    },
    capstone: {
      backLink: "← 返回团队项目",
      tagLabel: "CAPSTONE 毕业项目（占位）",
      gameName: "Box Shot",
      image: "../images/project-placeholder.svg",
      roleLabel: "角色",
      role: "占位",
      teamSizeLabel: "团队规模",
      teamSize: "占位",
      lengthLabel: "项目周期",
      length: "占位",
      platformLabel: "平台",
      platform: "占位",
      synopsisHeading: "游戏简介",
      synopsis: "占位文字 — 该项目详情待补充，准备好后替换为真实简介。",
      trailerHeading: "预告片",
      trailerNote: "占位 — 在此嵌入游戏预告片。",
      responsibilitiesHeading: "主要职责",
      responsibilities: ["占位文字 — 列出你的具体职责与贡献。"],
      screenshotsHeading: "游戏截图",
      screenshotsNote: "占位 — 添加游戏截图。",
      postmortemHeading: "项目复盘",
      postmortem: "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。",
    },

    individualProjects: {
      heading: "个人项目与认证",
      intro: "独立完成的作品，包括你的 DFS（定向研究）或毕业设计项目。",
      list: [
        {
          id: "fire",
          tag: "个人项目",
          name: "Fire",
          blurb: "占位文字 — 一句话描述，进行中的项目也可以放在这里。",
          href: "individual-projects/fire.html",
          image: "../images/project-placeholder.svg",
          placeholder: true,
        },
      ],
    },
    fire: {
      backLink: "← 返回个人项目",
      tagLabel: "个人项目（占位）",
      projectName: "Fire",
      image: "../images/project-placeholder.svg",
      roleLabel: "角色",
      role: "占位",
      teamSizeLabel: "团队规模",
      teamSize: "占位（如：独立完成）",
      lengthLabel: "项目周期",
      length: "占位",
      synopsisHeading: "项目简介",
      synopsis: "占位文字 — 描述这个项目，即使还在进行中也没关系。",
      responsibilitiesHeading: "主要职责",
      responsibilities: ["占位文字 — 列出你的具体职责与贡献。"],
      screenshotsHeading: "项目截图",
      screenshotsNote: "占位 — 添加项目截图。",
      postmortemHeading: "项目复盘",
      postmortem: "占位文字 — 回顾项目中做得好的地方、可以改进之处，以及你的收获。",
    },

    aboutPage: {
      pageTitle: "苟阳 — 关于我",
      heading: "关于我",
      photoAlt: "专业形象照占位",
      whoHeading: "我是谁、我在做什么",
      who: "我是一名拥有多年跨领域团队管理和流程优化经验的制作人。我将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种独特的结构化方法，擅长促成创意与设计部门之间的协作，交付打磨精良、机制扎实的项目。",
      howHeading: "我是如何走到这里的",
      how: "占位文字 — 简短讲讲你从建筑学转向游戏制作的故事（比如是什么吸引你从建筑转向游戏）。",
      nextHeading: "接下来想去哪里",
      next: "占位文字 — 描述你希望加入的角色、工作室或团队类型。",
      funHeading: "一些有趣的小事",
      fun: "占位文字 — 一两个轻松的个人细节（爱好、最喜欢的游戏等），展现你的个性。",
    },

    skills: {
      heading: "技能",
      items: [
        "项目管理",
        "Jira",
        "敏捷开发",
        "Lark 飞书",
        "Excel",
        "PowerPoint",
        "Unreal Engine 5 (UE5)",
        "Unity",
      ],
      languagesLabel: "语言",
      languages: ["英语", "中文（普通话）"],
    },
    experience: {
      heading: "工作经历",
      items: [
        {
          title: "系统设计实习生",
          org: "莉莉丝游戏 (Lilith Games)",
          location: "中国上海",
          dates: "2025.04 — 2025.08",
          bullets: [
            "为《AFK Arena（剑与远征）》项目设计系统，与多专业团队协作，优化大型 SLG 玩法机制以提升玩家参与度。",
            "开发并平衡新的 PvP 排位系统，与负责人及相关方沟通目标，提升竞技玩法体验。",
          ],
        },
        {
          title: "建筑设计实习生",
          org: "中国西南建筑设计研究院 (CSWADI)",
          location: "中国成都",
          dates: "2022.08 — 2022.11",
          bullets: [
            "完成三份初步设计方案，向相关方汇报提案，深化建筑细节，并最终确定四川大学华西第二医院的立面设计，提升项目与客户愿景的契合度。",
          ],
        },
      ],
    },
    education: {
      heading: "教育背景",
      items: [
        {
          degree: "硕士：交互技术 · 数字游戏开发 — 制作方向",
          school: "南卫理公会大学 (SMU) Guildhall",
          location: "美国德克萨斯州达拉斯",
          dates: "预计 2027.06 毕业",
        },
        {
          degree: "建筑学学士",
          school: "天津大学",
          location: "中国天津",
          dates: "2023.06",
        },
      ],
    },

    blog: {
      heading: "文章",
      viewAll: "查看全部文章 →",
      recentLabel: "最新文章",
      viewAllPosts: "查看全部文章 →",
      items: [
        {
          slug: "lessons-from-gearbox",
          title: "Gearbox 拜访笔记",
          date: "日期待定",
          category: "职业发展",
          excerpt: "一次 Gearbox 工作室拜访的笔记——聊反馈、沟通，以及制作人工作的本质。",
          pullQuote: "友谊铸就上线——但这不代表什么都要替他们做。",
          body: [
            "上周我们见了 Gearbox 的执行制作人 J. Low，以及制作助理总监 Lou。",
            "他们都身处“高层”位置，给我的第一印象是，他们的沟通方式和之前接触过的制作人很不一样——非常直接，几乎没有一句废话。这让我开始反思，自己是不是有时候只是“为了沟通而沟通”，说得多并不代表沟通得好。除了口头表达，他们两位都会用手绘的方式更准确地传达想法，这让我想起做建筑师时，我们也常用手绘和客户沟通。已经很久没再用这个方法了，具体为什么停下来的我也记不清，但我觉得是时候把它重新捡回来，当作沟通的“武器”。",
            "我们聊了很多关于职业发展的话题。",
            "怎么接受反馈？J. Low 说每个人都有自己的盲区，要多想“我没看到的是什么”，对反馈保持开放，尤其是那些来自你不太合得来的人的反馈，往往最有价值。收到反馈后，要想清楚背后的原因：如果是负面反馈——为什么？它是建设性的吗？我该怎么改？如果还是不理解，就直接去找对方聊。",
            "怎么给反馈？直接、有建设性。Lou 说完全不需要用“表扬三明治”的方式，这一点我很认同。但直接不代表刻薄，我还是会带着对对方贡献的认可去给反馈。",
            "Lou 还提到了“能力四阶段”：无意识的不胜任、有意识的不胜任、有意识的胜任、无意识的胜任。我们其实一直在这个循环里打转。",
            "Lou 也聊到了职业生涯中的“共情转变”，说实话我现在还不太清楚该怎么应对，但我猜等真正进入行业后会更有体会。",
            "制作人的工作到底是什么？这是我们讨论的另一个大问题。一句话总结：“维持住势头（momentum）”。很多新人制作人最容易掉进的一个陷阱，是对团队或组长投入过多情绪。“友谊铸就上线（Friendship leads to ship）”，但这不代表什么都要替他们做。学会给自己的工作做取舍很关键，因为每次晋升，工作本身都会变。",
            "最后是一些简历方面的建议：不放照片、不要用 AI 写求职信、多用强动词（比如“我推动了…”），少用被动表达（比如“我参与了…”）。这一条对我触动很大。",
          ],
        },
        { title: "占位文章标题", date: "日期", category: "设计" },
        { title: "占位文章标题", date: "日期", category: "复盘" },
      ],
    },
    personalProjects: {
      heading: "个人作品",
      intro: "占位文字 — 课余/工作之外的个人项目、游戏 Jam 或探索性作品。",
      items: [{ title: "占位项目", blurb: "占位文字 — 简短描述。", href: "#" }],
    },

    contact: {
      heading: "联系方式",
      lead: "欢迎聊聊游戏、团队或合作机会。",
      locationLabel: "所在地",
      location: "美国德克萨斯州达拉斯 75206",
      emailLabel: "邮箱",
      email: "younago@foxmail.com",
      websiteLabel: "网站",
      website: "www.gogo.fyi",
    },
    footer: {
      note: "用心打造，保留所有权利。",
    },
    resumePage: {
      pageTitle: "苟阳 — 简历",
      title: "简历",
      roleTag: "游戏制作人",
      downloadPdf: "下载 PDF",
      backHome: "← 返回主页",
      embedHeading: "简历内嵌预览（PDF）",
      embedNote: "已根据你的简历草稿生成。之后若有新版本，直接替换项目里的 resume.pdf 文件即可自动更新这里的预览。",
      summaryHeading: "简介",
      summary:
        "拥有多年跨领域团队管理和流程优化经验的制作人。将建筑学背景与游戏系统设计专长相结合，为项目统筹、范围管理和跨部门沟通带来一种独特的结构化方法。",
      contactHeading: "联系方式",
      experienceHeading: "工作经历",
      educationHeading: "教育背景",
      skillsHeading: "技能",
      projectsHeading: "代表项目",
    },
  },
};

// Expose for other scripts (plain <script> tags, no bundler)
window.SITE_CONTENT = SITE_CONTENT;
