(function () {
  "use strict";

  var dirHandle = null;
  var data = null; // { en: {...}, zh: {...} }
  var currentLang = "en";
  var dirty = false;

  var statusEl = document.getElementById("status");
  var openBtn = document.getElementById("openBtn");
  var reloadBtn = document.getElementById("reloadBtn");
  var saveBtn = document.getElementById("saveBtn");
  var welcomeEl = document.getElementById("welcome");
  var editorRootEl = document.getElementById("editorRoot");
  var formHost = document.getElementById("formHost");
  var unsupportedEl = document.getElementById("unsupported");

  function setStatus(text, kind) {
    statusEl.textContent = text;
    statusEl.className = kind || "";
  }

  function setDirty(v) {
    dirty = v;
    saveBtn.disabled = !v;
    if (v) setStatus("有未保存的改动", "");
  }

  // ---------------------------------------------------------------------
  // Feature detection
  // ---------------------------------------------------------------------
  if (!window.showDirectoryPicker) {
    unsupportedEl.classList.remove("hidden");
    openBtn.disabled = true;
  }

  // ---------------------------------------------------------------------
  // Traverse helper directory handles
  // ---------------------------------------------------------------------
  async function getDirHandle(root, relPathParts, create) {
    var h = root;
    for (var i = 0; i < relPathParts.length; i++) {
      h = await h.getDirectoryHandle(relPathParts[i], { create: !!create });
    }
    return h;
  }

  async function getFileHandle(root, relPath, create) {
    var parts = relPath.split("/");
    var fileName = parts.pop();
    var dh = await getDirHandle(root, parts, create);
    return dh.getFileHandle(fileName, { create: !!create });
  }

  // ---------------------------------------------------------------------
  // Load js/content.js, extract the SITE_CONTENT object literal, eval it
  // ---------------------------------------------------------------------
  async function loadContent() {
    var fh = await getFileHandle(dirHandle, "js/content.js", false);
    var file = await fh.getFile();
    var text = await file.text();
    var match = text.match(/const SITE_CONTENT\s*=\s*(\{[\s\S]*\n\});?\s*\/\/ Expose/);
    if (!match) {
      // fallback: grab from first { to the last '};' before window.SITE_CONTENT
      var startIdx = text.indexOf("const SITE_CONTENT");
      var braceIdx = text.indexOf("{", startIdx);
      var endMarker = text.indexOf("window.SITE_CONTENT");
      var lastBrace = text.lastIndexOf("};", endMarker);
      if (braceIdx === -1 || lastBrace === -1) throw new Error("无法解析 content.js，文件结构和预期不一致");
      match = [null, text.slice(braceIdx, lastBrace + 1)];
    }
    var objLiteral = match[1];
    // eslint-disable-next-line no-new-func
    var parsed = new Function("return (" + objLiteral + ");")();
    data = parsed;
  }

  function serializeContent() {
    var body = JSON.stringify(data, null, 2);
    return (
      "// ---------------------------------------------------------------------------\n" +
      "// All editable site copy lives here, in English and Chinese.\n" +
      "// This file is regenerated by editor.html — hand-written comments here will\n" +
      "// be lost on save, but the data structure and all page scripts are unaffected.\n" +
      "// ---------------------------------------------------------------------------\n\n" +
      "const SITE_CONTENT = " + body + ";\n\n" +
      "// Expose for other scripts (plain <script> tags, no bundler)\n" +
      "window.SITE_CONTENT = SITE_CONTENT;\n"
    );
  }

  async function saveContent() {
    var text = serializeContent();
    var fh = await getFileHandle(dirHandle, "js/content.js", false);
    var writable = await fh.createWritable();
    await writable.write(text);
    await writable.close();
  }

  // ---------------------------------------------------------------------
  // Image upload: writes into images/ under the site root, returns the
  // root-relative path ("images/filename.ext") to store in the data field.
  // ---------------------------------------------------------------------
  function sanitizeFileName(name) {
    return name.replace(/[^a-zA-Z0-9._-]/g, "-").toLowerCase();
  }

  async function saveImageFile(file) {
    var imagesDir = await getDirHandle(dirHandle, ["images"], true);
    var name = sanitizeFileName(file.name);
    var fh = await imagesDir.getFileHandle(name, { create: true });
    var writable = await fh.createWritable();
    await writable.write(file);
    await writable.close();
    return "images/" + name;
  }

  // Convert a stored path (which may be root-relative "images/x" or
  // "../images/x" from a subfolder page) into something we can preview
  // and eventually re-derive the same style of prefix for.
  function imagePrefix(path) {
    var m = /^(\.\.\/)*images\//.exec(path || "");
    return m ? m[0].replace(/images\/$/, "") : "";
  }

  async function previewSrcFor(path) {
    try {
      var m = /(?:\.\.\/)*images\/(.+)$/.exec(path);
      if (!m) return null;
      var imagesDir = await getDirHandle(dirHandle, ["images"], false);
      var fh = await imagesDir.getFileHandle(m[1], { create: false });
      var file = await fh.getFile();
      return URL.createObjectURL(file);
    } catch (e) {
      return null;
    }
  }

  // ---------------------------------------------------------------------
  // Generic recursive form renderer
  // path: array of keys/indices from data[currentLang]
  // ---------------------------------------------------------------------
  function getRoot() {
    return data[currentLang];
  }

  function getAt(path) {
    return path.reduce(function (acc, k) { return acc == null ? acc : acc[k]; }, getRoot());
  }

  function setAt(path, value) {
    var obj = getRoot();
    for (var i = 0; i < path.length - 1; i++) obj = obj[path[i]];
    obj[path[path.length - 1]] = value;
    setDirty(true);
  }

  function labelFor(key) {
    return key;
  }

  function isImageKey(key) {
    return key === "image" || key === "portrait";
  }

  function renderValue(container, value, path, key) {
    if (isImageKey(key) && typeof value === "string") {
      renderImageField(container, value, path);
      return;
    }
    if (typeof value === "string") {
      renderStringField(container, value, path, key);
      return;
    }
    if (typeof value === "boolean") {
      renderBoolField(container, value, path, key);
      return;
    }
    if (Array.isArray(value)) {
      renderArrayField(container, value, path, key);
      return;
    }
    if (value && typeof value === "object") {
      renderObjectField(container, value, path, key);
      return;
    }
  }

  function renderStringField(container, value, path, key) {
    var field = document.createElement("div");
    field.className = "field";
    var label = document.createElement("label");
    label.textContent = labelFor(key);
    field.appendChild(label);
    var input;
    if (value.length > 70 || value.indexOf("\n") !== -1) {
      input = document.createElement("textarea");
    } else {
      input = document.createElement("input");
      input.type = "text";
    }
    input.value = value;
    input.addEventListener("input", function () {
      setAt(path, input.value);
    });
    field.appendChild(input);
    container.appendChild(field);
  }

  function renderBoolField(container, value, path, key) {
    var field = document.createElement("div");
    field.className = "field checkbox-field";
    var id = "chk-" + path.join("-");
    var input = document.createElement("input");
    input.type = "checkbox";
    input.id = id;
    input.checked = value;
    input.addEventListener("change", function () {
      setAt(path, input.checked);
    });
    var label = document.createElement("label");
    label.setAttribute("for", id);
    label.textContent = labelFor(key);
    field.appendChild(input);
    field.appendChild(label);
    container.appendChild(field);
  }

  function renderImageField(container, value, path) {
    var field = document.createElement("div");
    field.className = "field image-field";

    var img = document.createElement("img");
    img.alt = "";
    previewSrcFor(value).then(function (src) { if (src) img.src = src; });
    field.appendChild(img);

    var col = document.createElement("div");
    var pathEl = document.createElement("div");
    pathEl.className = "path";
    pathEl.textContent = value;
    col.appendChild(pathEl);

    var fileInput = document.createElement("input");
    fileInput.type = "file";
    fileInput.accept = "image/*";
    fileInput.addEventListener("change", async function () {
      if (!fileInput.files || !fileInput.files[0]) return;
      var savedPath = await saveImageFile(fileInput.files[0]);
      var prefix = imagePrefix(value);
      var newValue = prefix + savedPath;
      setAt(path, newValue);
      pathEl.textContent = newValue;
      var src = await previewSrcFor(newValue);
      if (src) img.src = src;
    });
    col.appendChild(fileInput);
    field.appendChild(col);
    container.appendChild(field);
  }

  function renderArrayField(container, arr, path, key) {
    var fs = document.createElement("fieldset");
    var legend = document.createElement("legend");
    legend.textContent = labelFor(key) + " (" + arr.length + ")";
    fs.appendChild(legend);

    arr.forEach(function (item, idx) {
      var itemPath = path.concat(idx);
      var itemWrap = document.createElement("div");
      itemWrap.className = "list-item";

      var removeBtn = document.createElement("button");
      removeBtn.className = "remove-btn";
      removeBtn.textContent = "删除";
      removeBtn.addEventListener("click", function () {
        arr.splice(idx, 1);
        setDirty(true);
        renderForm();
      });
      itemWrap.appendChild(removeBtn);

      if (typeof item === "string") {
        renderStringField(itemWrap, item, itemPath, "#" + (idx + 1));
      } else if (item && typeof item === "object") {
        Object.keys(item).forEach(function (subKey) {
          renderValue(itemWrap, item[subKey], itemPath.concat(subKey), subKey);
        });
      }
      fs.appendChild(itemWrap);
    });

    var addBtn = document.createElement("button");
    addBtn.className = "add-btn";
    addBtn.textContent = "+ 添加一项";
    addBtn.addEventListener("click", function () {
      var template = arr.length > 0 ? arr[arr.length - 1] : (typeof arr[0] === "object" ? {} : "");
      var clone = typeof template === "object" && template !== null
        ? JSON.parse(JSON.stringify(template))
        : "";
      if (typeof clone === "object") {
        Object.keys(clone).forEach(function (k) {
          if (typeof clone[k] === "string") clone[k] = "";
          if (typeof clone[k] === "boolean") clone[k] = false;
        });
      }
      arr.push(clone);
      setDirty(true);
      renderForm();
    });
    fs.appendChild(addBtn);

    container.appendChild(fs);
  }

  function renderObjectField(container, obj, path, key) {
    var fs = document.createElement("fieldset");
    var legend = document.createElement("legend");
    legend.textContent = labelFor(key);
    fs.appendChild(legend);
    Object.keys(obj).forEach(function (k) {
      renderValue(fs, obj[k], path.concat(k), k);
    });
    container.appendChild(fs);
  }

  function renderForm() {
    formHost.innerHTML = "";
    var root = getRoot();
    Object.keys(root).forEach(function (key) {
      renderValue(formHost, root[key], [key], key);
    });
  }

  // ---------------------------------------------------------------------
  // Top-level controls
  // ---------------------------------------------------------------------
  document.querySelectorAll(".lang-tabs button").forEach(function (btn) {
    btn.addEventListener("click", function () {
      document.querySelectorAll(".lang-tabs button").forEach(function (b) { b.classList.remove("active"); });
      btn.classList.add("active");
      currentLang = btn.getAttribute("data-lang");
      renderForm();
    });
  });

  openBtn.addEventListener("click", async function () {
    try {
      dirHandle = await window.showDirectoryPicker();
      await loadContent();
      welcomeEl.classList.add("hidden");
      editorRootEl.classList.remove("hidden");
      reloadBtn.disabled = false;
      setDirty(false);
      setStatus("已打开：" + dirHandle.name, "ok");
      renderForm();
    } catch (e) {
      if (e && e.name === "AbortError") return;
      setStatus("打开失败：" + e.message, "err");
    }
  });

  reloadBtn.addEventListener("click", async function () {
    if (dirty && !confirm("重新读取会丢弃当前未保存的改动，确定吗？")) return;
    try {
      await loadContent();
      setDirty(false);
      setStatus("已重新读取", "ok");
      renderForm();
    } catch (e) {
      setStatus("读取失败：" + e.message, "err");
    }
  });

  saveBtn.addEventListener("click", async function () {
    try {
      await saveContent();
      setDirty(false);
      setStatus("已保存 ✓ 刷新网页查看效果", "ok");
    } catch (e) {
      setStatus("保存失败：" + e.message, "err");
    }
  });

  window.addEventListener("beforeunload", function (e) {
    if (dirty) {
      e.preventDefault();
      e.returnValue = "";
    }
  });
})();
